server/app.js

When refreshing the page in the production environment, the app fails with the message
```
Cannot GET /personality/5ebdd0c09f9292005890d4c4
```
Because there is a conflict between react-router and express routes, this is addressed by serving the static html to every route using a wild card.

Fix Express and React router conflict

---

src/api/personality.js
src/components/Claim/ClaimCard.jsx
src/components/Personality/PersonalityCard.jsx
src/components/Personality/PersonalityList.jsx
src/components/Personality/PersonalityView.jsx
src/i18n.js

Merge after https://github.com/OpenTesseract/aletheia/pull/113 is merged
1) Move ClaimCard to its own file
2) Use new data from personality endpoint and comply to the UI specs for
the personality card
3) Add i18n for the personality profile button
4) Apply changes to personality card at the home page

Display personality card according to layout

---

.vscode/tasks.json

As a good part of the team is using VS Code, I think it is useful to
execute just one command to get the project ready to work.
The default shortcut in VS Code is `Ctrl` + `Shift` + `B`. In my case, I
assigned it to the `F6` key. It is really quite useful.
``` sh
yarn \
&& yarn build \
&& yarn dev:server \
& yarn dev:front
```
- [&&' vs. '&' with the 'test' command in Bash](https://stackoverflow.com/a/26770612/1096219)

feat(vscode): Add tasks.json to speed up dev build

---

package.json
server/api/repository/claim.ts
server/api/repository/personality.ts
server/lib/parser.ts
server/routes/personality.js
src/App.js
src/components/Claim/ClaimCreate.jsx
yarn.lock

1) Make ClaimCreate able to receive a boolean prop to indicate whether
the component should render in edit mode or not
2) Store html for Claim again in order to restore the right EditorState
when editing the claim
3) Apply parser to content submitted through PUT endpoint for claim
4) Bonus: Fix error in personality list endpoint
PS: The edit page is avaible but not exposed in the UI yet.

claim: Edit page

---

src/components/AletheiaSocialMediaFooter.tsx

-  Set target blank on SocialIcon to open links on new tabs
- Click on social media icons in the footer of a page and check that it opens on new tab
Closes #253

Open social media links in new tabs

---

public/locales/en/notFound.json
public/locales/pt/notFound.json
server/app.module.ts
server/filters/not-found.filter.ts
server/view/view.controller.ts
src/components/Aletheia404.tsx
src/pages/404-page.tsx

- Added a custom 404 page
- Added a exception filter on the server to handle not found exceptions redirecting to our custom 404 page
- Try to acces to a page that doesn't exist in our domain  ([example](http://localhost:3000/lalala)) and check that it displays a custom 404 page.
Closes #247

Show custom 404 page

---

src/components/Login/LoginView.tsx
src/pages/login.tsx

- Uses the referrer of login page to determine if router shouldreturn or redirect to the home page after login
- Access the login page from a link within our domain, such as the link in the side menu, after a successful login you should be redirected to the previous page. 
- Access the login page by typing in the address bar or from a link outside our domain, after a successful login you should be redirected to the home page.
Closes #257

Fix redirect after login

---

src/components/List/BaseList.tsx

- Change the condition to show the "load more" button only while the total is greater than the number of pages loaded
- Go to a page with a list and check if the "load more" button only appears if there are more items to be loaded
Closes #256

Fix condition to show 'load more' button

---

src/components/ClaimReview/ClaimSentenceCard.tsx

- Remove ellipsis from claim review content paragraph
- Go to a Claim Review page for a paragraph longer than 4 lines and check if the ellipsis appear at the end of the sentence
Closes #254

Remove ellipsis from claim review content

---

public/locales/en/claim.json
public/locales/pt/claim.json
src/components/Claim/ClaimCard.tsx
src/components/Claim/ClaimCardHeader.tsx
src/components/ClaimReview/ClaimReviewView.tsx
src/components/ClaimReview/ClaimSentenceCard.tsx

Add personality description and speech information to the claim header.
Closes #292

Finish UI: Claim Card Header

---

server/main.ts
server/seed.ts

fix mongodb warnings
Node] (node:13216) [MONGODB DRIVER] Warning: the options [useCreateIndex] is not supported
[Node] (node:13216) [MONGODB DRIVER] Warning: the options [useFindAndModify] is not supported

fix mongoDB warnings

---

src/pages/_document.tsx

Fix the Warning: useLayoutEffect does nothing on the server by replacing useLayoutEffect with useEffect when the document has not yet been created.
Closes #258

Fix useLayoutEffect warning

---

config.seed.example.yaml
server/users/users.service.ts

if the script finds an oryId prop in the config.seed.yaml it wont try to create the ory identity and just save the user in the database.
Closes #490

Update the seed script to work with Ory

---

src/components/Content.style.tsx
src/components/MainApp.tsx

[Server] The component MainApp__ContentStyled with the id of "MainApp__ContentStyled-sc-bt5ql1-0" has been created dynamically.
[Server] You may see this warning because you've called styled inside another component.
[Server] To resolve this only create new StyledComponents outside of any render method and function component.
DONE IN https://github.com/AletheiaFact/aletheia/pull/419/commits/9f5477c509ba5a1d1a3e924f135a888301c5dabd#diff-dafb385ddc854a6641b15ca8f53c6a9c5382cba40fce3e944ac0b92204bc68af, when creating a new file to separate the styledComponents
[Server] Warning: Received `true` for a non-boolean attribute `mobile`.
DONE IN THIS PR
closes #511

mainApp bug fix #511

---

server/claim-revision/claim-revision.service.ts
server/claim/claim.service.ts

Previously when we tried to get a specific revision of a claim and provided an revision id of another claim, we are not redirected to 404 page

fixed bug when get specific revisions

---

src/components/Home/HomeCarousel.style.tsx
src/components/Home/HomeCarousel.tsx
src/hooks/useMediaQuery.ts

- Created a custom hook to allow us to use media queries outside of styled components or style props.
- Used the new hook to adjust the object-fit and object-position of the carousel image when the window is smaller than 768px, which is the ant design's breakpoint between small and medium.
400px
700px 
1440px

Fix mobile carousel

---

public/locales/en/personality.json
public/locales/pt/personality.json
server/personality/personality.service.ts
server/util.ts
src/components/AletheiaTitle.tsx
src/components/Metrics/ReviewProgress.tsx
src/components/Metrics/ReviewStats.tsx

Show see all button when we have more than 3 different classifications, create components for title and review, don't slice reviews anymore in backend
closes #567

Fix metrics overview

---

cypress/fixtures/claim.ts
cypress/fixtures/example.json
cypress/fixtures/personality.ts
cypress/fixtures/review.ts
cypress/fixtures/user.ts
cypress/integration/tests/home.spec.ts
cypress/integration/tests/personality.spec.ts
cypress/integration/tests/review.spec.ts
cypress/support/commands.ts
cypress/support/locators.ts

This should make it easier to maintain tests by separating out any data that will be typed, such as the content of claims and reviews, or variable text that will be checked, such as the slugs of personality names and claim titles

Reorganize tests to use fixture files

---

server/main.ts

Fix collection.ensureIndex MongoDB deprecation warning
```
(node:49) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use node --trace-deprecation ... to show where the warning was created)
```
closes #588

Fix MongoDB deprecation warning

---

server/sitemap/sitemap.service.ts

Fix the url for claim reviews in the sitemap by getting the correct nested prop of the review object.
Change the priority for the review page from 0.9 to 1, the highest possible.
Closes #641

Fix sentence hash in sitemap

---

src/components/Claim/ClaimCard.tsx
src/components/Claim/ClaimSentence.tsx

Added space between sentences in the claim page and claim card

---

server/claim-review-task/claim-review-task.controller.ts
server/claim-review-task/claim-review-task.service.ts

- Since we save machine value as an object we need to query by key value
- Now we can differentiate if the task is in draft or not

Fix kanban query error

---

server/claim-review-task/claim-review-task.service.ts

- when the task is published it didn't appear in kanban

Fix Published tasks kanban error

---

server/claim-review/claim-review.service.ts
server/claim/claim.controller.ts
server/claim/claim.service.ts
server/personality/personality.controller.ts
server/personality/personality.service.ts
server/sentence/sentence.module.ts
server/sentence/sentence.service.ts
src/components/ClaimReview/ClaimReviewView.tsx
src/components/ClaimReview/ClaimSentenceCard.tsx
src/pages/claim-review.tsx

- remove _getSentenceByHashAndClaimId function, since now we query claim review, which has the same fields
- create getPersonalityBySlug which just returns personality without population
- do the same to query the claim function
- remove unused getReviewStatsBySentenceHash() 'cause will be always one review/stats
- when get a sentence to try to inject classification into props
- remove useless code in claimReviewView

Refactor getClaimReviewPage

---

server/claim/claim.controller.ts
src/components/AletheiaCaptcha.tsx
src/lib/recaptcha.ts
src/pages/claim-create.tsx
src/pages/claim-page.tsx
src/pages/claim-review.tsx
src/store/actions.ts
src/store/store.ts
src/store/types.ts

Given some problems on the production environment we decided to go back to send the sitekey from the backend, but to avoid prop drilling we store the value in redux and only access it in the captcha component

The captcha component gets the sitekey from redux

---

package.json
yarn.lock

Bump json5 from 1.0.1 to 1.0.2
Bump deep-object-diff from 1.1.7 to 1.1.9
Bump loader-utils from 1.4.0 to 1.4.2
Bump luxon from 1.28.0 to 1.28.1
Bump class-validator from 0.13.2 to 0.14.0
Bump ua-parser-js from 0.7.31 to 0.7.33
Bump cookiejar from 2.1.3 to 2.1.4
Bump decode-uri-component from 0.2.0 to 0.2.2

Dependabot bump versions

---

migrations/20221202183435-claimreviewtasks-renameSentenceHash.ts

When testing the migration against the production database it failed because the data_hash index was already created, so now we check if the index is present before creating it

Check if index is present before creating it

---

src/components/Personality/PersonalityCard.tsx
src/components/Personality/PersonalityCreateSearch.tsx
src/components/Personality/PersonalitySearchResultSection.tsx

Avoid create more than one personality at once by quickly clicking on the add personality buttons.
closes #891

Fixed creating two different personalities at once

---

migrations/20230425092159-fix_debate_transition.ts
server/claim-review-task/claim-review-task.controller.ts
server/claim-review-task/claim-review-task.service.ts
server/mongo-pipelines/lookUpPersonalityties.ts
server/mongo-pipelines/lookupClaimReviews.ts
server/mongo-pipelines/lookupClaimRevisions.ts
server/mongo-pipelines/lookupClaims.ts
server/mongo-pipelines/lookupUsers.ts

- fixed debate_transition migration, setting isDeleted field
- extract lookup stage in separate helper functions
- create count function that counts kanban elements that arent deleted
- change method .find to aggreation pipeline
- filter the results of the aggregation to bring just claimReviewTasks that doesnt have claim or claim-reviews deleted

Fixed Error on Kanban page at Aletheia Production

---

public/locales/en/header.json
public/locales/en/home.json
public/locales/pt/header.json
public/locales/pt/home.json
src/components/Header/DonateButton.tsx
src/components/Header/Header.tsx
src/components/Header/HeaderActions.style.tsx
src/components/Header/HeaderContent.tsx
src/components/Header/Menu.tsx
src/components/Header/SelectLanguage.tsx
src/components/Header/UserMenu.tsx
src/components/Home/CTASection.style.tsx
src/components/Home/CTASection.tsx
src/components/Home/HomeHeader.style.tsx
src/components/Home/HomeHeader.tsx
src/components/Home/Stats.tsx
src/components/Search/SearchOverlay.tsx

Created Donate Button and Improved Home_header responsive design

---

public/locales/en/unauthorized.json
public/locales/pt/unauthorized.json
server/auth/session.guard.ts
src/components/AccessDeniedPage.tsx
src/pages/access-denied-page.tsx

Depriving Regular Users of Acess The Platform When It is Private

---

server/claim-review/claim-review.service.ts
server/claim-review/dto/create-claim-review.dto.ts
server/claim-review/schemas/claim-review.schema.ts

if the claim doesn't have a personality, save the document with the personality property as null not a random Id
closes #991

Fixed claimReview creation of claims without personality

---

public/locales/en/menu.json
public/locales/pt/menu.json
src/components/AletheiaMenu.tsx

- adicionei links no menu para pagina de personalidade, afirmação e kanban
closes #984

Added to the Menu the link to the kanban page

---

server/claim-review-task/claim-review-task.controller.ts
server/claim-review-task/claim-review-task.service.ts

- fixed filter tasks with two or more users.
- fixed count when filtering users
closes #1012

Fixed Filter my tasks in kanban when task does have more than 1 user assignee

---

lib/editor-parser.ts

Old sources in the report will break with the new source structure. We need to add a backwards compatibility change and work on a proper migration for the data in an follow-up PR.

Hotfix: Reports with old source structure are not rendering in the claim review page

---

src/components/ClaimReview/ClaimReviewView.tsx
src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
src/components/ClaimReview/form/hooks/useAutoSaveDraft.tsx
src/components/Toolbar/AdminToolBar.tsx
src/components/Toolbar/ReviewTaskAdminToolBar.tsx
src/machines/reviewTask/ReviewTaskMachineProvider.tsx
src/machines/reviewTask/enums.ts
src/machines/reviewTask/reviewTaskMachine.ts
src/machines/reviewTask/selectors.ts

- Create reviewTask admin tool bar
- Move setFormAndEvents function to globalContext file
- Add reAssignUser Event
---

Allow admins re-assign a fact-checker to a task

---

server/auth/name-space/dto/create-namespace.dto.ts
server/auth/name-space/name-space.controller.ts
server/auth/name-space/name-space.service.ts

For some reason when we were importing the `user.service` in the `name-space.service` module class, the `namespace.guard.ts` stopped to work, since the guard injects the `name-space service`. So i moved the logic that was dependent from the `user-service` to the `name-space.controller` file

Fixed namespace guard

---

src/components/Profile/Totp.tsx

CTA Button's text responsive in small screens

---

public/locales/pt/debates.json

Language error corrected in the text of the isended debate

---

server/personality/personality.service.ts
server/sitemap/sitemap.service.ts
server/wikidata/wikidata.service.ts

Resolved an issue where the `sitemap.xml` was not being properly generated or accessible in the production environment. This fix ensures that the sitemap is correctly generated and can be accessed by search engines, allowing the site to be indexed by Google.
- Updated the sitemap generation script to run correctly in the production environment.
This change should improve the site's visibility in search engine results.

Fix: ensure sitemap.xml is accessible in production environment

---

src/components/adminArea/Drawer/UserEditRoles.tsx

Adicionar cor condicional para refletir a cor com base no ambiente do namespace no  UserEditRoles.

issues1170-addColorConditional

---

src/components/Collaborative/Comment/CommentCardContent.tsx
src/components/Collaborative/Comment/CommentContainer.tsx
src/components/Collaborative/utils/usePluginReady.ts

- Introduced a custom hook `usePluginReady` to modularize and reuse the logic for polling the annotation plugin's readiness across multiple components.
- Implemented polling to ensure that the annotation plugin is fully initialized before being accessed. This prevents errors when the plugin loads slower than the rest of the page.
- Replaced inline polling logic in `CommentCardContent` and `CommentContainer` components with the new reusable `usePluginReady` hook.
- Improved code readability and maintainability by avoiding duplicated logic and centralizing the plugin readiness check.
Fixes #1379

feat/fix: Add polling mechanism for annotation plugin initialization when annotations are enabled

---

src/components/topics/TopicDisplay.tsx

Adding a debouncing mechanism ensures that the function is only executed after a period of inactivity. This prevents the function from running with each character.
Example:
closes #1326

Adding a debouncing mechanism when searching wikidata topics

---

src/components/Header/Logo.tsx
src/components/Header/LogoAletheia.tsx

*This width is unnecessary because by defining only the height, the width will be proportional. It was breaking on the platform of some volunteers.*
before in some volunteers:
after:

Remove width unnecessary in svg 

---

src/components/ClaimReview/ClaimReviewView.tsx

*ClaimReviewView.tsx: Refactor ClaimReviewHeader rendering: add conditional helper functions, `isClaimTypeAndNotSmallScreen` to check if the review task type is "Claim" and screen size is not small, or if the task has not started, or if the user is not a regular user and `isSourceOrVerificationRequest` to validate if the review task type is "Source" or "VerificationRequest". Applied combined conditional rendering for `ClaimReviewHeader` using `(isClaimTypeAndNotSmallScreen || isSourceOrVerificationRequest)`*
Fixes #1427  #1433  #1436 
*- Tested in Source Page, Verification Request Page and Claim Page, all pages are working on screens smaller than 768px and 425px, no longer breaking the Claim Review Header component.
- Also certified in space …

Issues 1427/1433/1436 - Bug Display below 768px and Condicional User Permissions in Sentence

---

server/auth/ory/ory.controller.ts
server/auth/ory/ory.service.ts

The login flow is not working locally when using a Ory Cloud development instance. The reason was because the cookie was hardcoded to work specifically with a local kratos instance. Now we are just forwarding the cookie to the `/whoami` call and it should work with every type of instance.
before:
after:

Resolving ory login bug

---

src/components/Claim/ClaimSummaryContent.tsx
src/components/Claim/CreateClaim/ClaimSelectType.tsx
src/components/ClaimReview/ReviewAlert.tsx
src/components/ClaimReview/ReviewCard.tsx
src/components/Collaborative/Comment/CommentPopoverContent.tsx
src/components/Collaborative/Components/SourceEditorButton.tsx
src/components/Collaborative/Form/EditorCard.tsx
src/components/Collaborative/Form/QuestionCard.tsx
src/components/Dashboard/DashboardView.tsx
src/components/Footer/AletheiaSocialMediaIcons.tsx
src/components/Header/HeaderActions.style.tsx
src/components/Header/HeaderContent.tsx
src/components/Home/CTA/CTASectionButtons.tsx
src/components/Home/CTA/CTASectionTitle.tsx
src/components/Home/DonationBanner.style.tsx
src/components/Home/DonationBanner.tsx
src/components/Home/HomeFeed.tsx
src/components/Home/HomeHeader/HomeHeader.style.tsx
src/components/Home/HomeStats.tsx
src/components/LoginButton.tsx
src/components/adminArea/Drawer/HeaderTotpStatus.tsx
src/components/adminArea/Drawer/HeaderUserStatus.tsx

*In this PR, I addressed all the issues created during the switch from Ant to MUI that involved importing only { Col } and { Row }. I adapted them to use { Grid } from MUI without losing the standard layout. This way, we can resolve issues that require similar and/or minor changes.*
*You should go to each component where the switch from Ant to MUI was made and test the design and responsiveness. In this case, since it involves replacing a component that handles columns, you only need to ensure that nothing is broken or out of place.*
Each components:
*A visual document outlining which visual parts of the site are intended to facilitate testing:*
[testing.pdf](https://github.com/user-attachments/files/18148995/testing.pdf)

Adapting imports of {Col} & {Row} alone to Grid/mui

---

src/components/AletheiaTitle.tsx
src/components/Claim/ClaimCard.tsx
src/components/Claim/ClaimCardHeader.tsx
src/components/Claim/ClaimInfo.tsx
src/components/Claim/ClaimView.tsx
src/components/ClaimReview/ReviewContent.tsx
src/components/CodeOfConduct/CodeOfConduct.tsx
src/components/Debate/DebateGrid.tsx
src/components/Footer/AletheiaSocialMediaIcons.tsx
src/components/Header/HeaderContent.tsx
src/components/Home/HomeStats.tsx
src/components/Label.tsx
src/components/Metrics/ReviewStats.tsx
src/components/Personality/MorePersonalities.tsx
src/components/Personality/PersonalityView.tsx
src/components/SectionTitle.tsx
src/components/SocialMediaShare.tsx
src/components/Subtitle.tsx

*In this PR, I replaced all Ant Design Typography components with MUI, and where necessary, I replaced Ant Design's Col, Row, Affix, and Comment components with their respective MUI equivalents.*
*I only replaced the typographs, but in some components, I also adjusted the responsiveness since I was already working on them.*
*Each component*
*A visual document outlining which visual parts of the site are intended to facilitate testing:*
[teste-typograph1.pdf](https://github.com/user-attachments/files/18223211/teste-typograph1.pdf)
closes #1481, #1514, #1685, #1684, #1519, #1522, #1523, #1532, #1533, #1534, #1554, #1538, #1552, #1573

Change all typography antd for muy

---

public/locales/en/sources.json
public/locales/pt/sources.json
src/api/badgesApi.ts
src/api/claim.ts
src/api/claimReviewApi.ts
src/api/comment.ts
src/api/dailyReport.ts
src/api/editor.ts
src/api/image.ts
src/api/namespace.ts
src/api/ory.ts
src/api/personality.ts
src/api/reviewTaskApi.ts
src/api/sentenceApi.ts
src/api/sourceApi.ts
src/api/topicsApi.ts
src/api/userApi.ts
src/api/verificationRequestApi.ts
src/components/Claim/CreateClaim/ClaimSelectPersonality.tsx
src/components/ImageUpload.tsx
src/components/Kanban/KanbanCard.tsx
src/components/Login/LoginView.tsx
src/components/Messages.tsx
src/components/Profile/Totp.tsx
src/components/VerificationRequest/VerificationRequestList.tsx
src/lib/orysdk/errors.ts
src/pages/_app.tsx

*In this PR, I created a message component to replace the native message from Ant Design, thus changing all the places where messages (success, error, warning, info) are used. The message component uses a Node.js class and provides a way to emit and listen to events in a decoupled manner, making it possible to use it globally across the platform, just like the Ant Design message. A natural style change was made, so it doesn't affect the user experience*
*style change:*
*All types of messages that appear on the site, whether error, success, warnings, or info, were changed, so I need to trigger all these situations to test the messages properly. Apart from that, I took the opportunity to change col, row, typography, and avatar, which I will separate here to make it easier.*
*API components* …

Change all messages antd for mui

---

src/components/Form/DynamicForm.tsx
src/components/SentenceReport/SentenceReportContent.style.tsx

Fixes a layout bug in the textarea containers, which were previously exceeding the expected design boundaries. The containers have now been adjusted to adhere to the predefined limits, ensuring a better visual and functional user experience.
Fixes [#1413](https://github.com/AletheiaFact/aletheia/issues/1413)
There is a sample video available showcasing the corrected layout.
https://jam.dev/c/5ad46da5-52b1-4471-8d68-0584ccc8c4b2
screen 768px
!![image](https://github.com/user-attachments/assets/baed02cf-eb16-4739-a402-5c7839b390ab)
1. Navigate to the screens with forms that contain text fields (textareas or inputs) to be filled.
2. Confirm that the containers for the text fields adhere to the predefined layout boundaries.
3. Ensure there is no …

fixed layout issue in the form containers.

---

src/components/SentenceReport/SourceSummaryDisplay.tsx
src/components/Source/ClaimSourceList.style.tsx
src/components/Source/ClaimSourceList.tsx
src/components/Source/ClaimSourceListItem.tsx
src/components/Source/CreateSource/CreateSourceView.tsx
src/components/Source/SourceList.tsx
src/components/Source/SourceListItem.style.tsx
src/components/Source/SourceListItem.tsx

*In this PR, I migrated the components from sources used in the platform to MUI Material. This mostly involved replacing `Col` and `Row` with `Grid` and adapting the `List` and `Typography` from Ant Design to MUI.*
*In this PR, I managed to separate the pages as we discussed. The `Col` and `Row` were replaced by `Grid`, and in relation to this, the site's responsiveness needs to be tested. You can test the list by creating sources both on the claims page and on the sentences page. I recommend creating four or more to make the testing more thorough. All the Typography from Ant Design was also replaced, so it’s necessary to check if there is any text that’s out of the pattern or breaking the design.*
**Components:** 
**A visual document outlining which visual parts of the site need to be …

Migrate components from sources used in the platform

---

src/components/Home/HomeHeader/HomeHeader.style.tsx
src/components/Home/HomeHeader/HomeHeader.tsx
src/components/Home/HomeHeader/HomeHeaderSearch.style.tsx
src/components/Home/HomeHeader/HomeHeaderSearch.tsx
src/components/Home/HomeHeader/HomeHeaderTitle.tsx
src/components/Kanban/EmptyKanbanGrid.tsx
src/components/Kanban/KanbanGrid.tsx
src/components/Kanban/KanbanToolbar.tsx
src/components/Kanban/KanbanView.tsx

*In this PR, I migrated the Kanban page and the HomeHeader to MUI Material. This mostly involved replacing `Col` with `Grid` and adapting the `Divider` from Ant Design to MUI.*
*In this PR, I managed to separate the pages as we discussed. The `Col` were replaced by `Grid`, and in relation to this, the site's responsiveness needs to be tested. The `divider` is a very subtle element used to separate items on the website. It looks like a line, and to test it, you just need to check if its design is correct and if it doesn’t break anything.*
**Components:**
**A visual document outlining which visual parts of the site need to be tested:**
[Guia visual testes 1.pdf](https://github.com/user-attachments/files/18464300/Guia.visual.testes.1.pdf)
*This guide was created while I was making the …

Migrate kanban and home header page to mui material 

---

src/components/SentenceReport/ClaimSummaryDisplay.tsx
src/components/SentenceReport/SentenceReportCard.style.tsx
src/components/SentenceReport/SentenceReportCard.tsx
src/components/SentenceReport/SentenceReportContent.style.tsx
src/components/SentenceReport/SentenceReportContent.tsx
src/components/SentenceReport/SentenceReportPreview.tsx
src/components/SentenceReport/SentenceReportPreviewView.tsx
src/components/SentenceReport/SentenceReportSummary.tsx
src/stories/components/sentenceReport/SentenceReportSummary.stories.tsx

*In this PR, I migrated the sentence report page to MUI Material. This mostly involved replacing `Col` and `Row` with `Grid` and adapting the `Divider` and `Typography` from Ant Design to MUI.*
*In this PR, I managed to separate the pages as we discussed. The `Col` and `Row` were replaced by `Grid`, and in relation to this, the site's responsiveness needs to be tested. The `divider` is a very subtle element used to separate items on the website. It looks like a line, and to test it, you just need to check if its design is correct and if it doesn’t break anything. All the Typography from Ant Design was also replaced, so it’s necessary to check if there is any text that’s out of the pattern or breaking the design.*
**Components:**
**A visual document outlining which visual parts of the site …

Migrate sentence report page

---

src/components/AletheiaCaptcha.tsx
src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
src/components/Collaborative/Components/Editor.style.tsx
src/components/Collaborative/Components/Editor.tsx
src/components/Form/DynamicForm.tsx
src/components/Toolbar/ReviewTaskAdminToolBar.tsx
src/components/topics/TagDisplay.style.tsx
src/components/topics/TagDisplay.tsx
src/components/topics/TagsList.tsx
src/components/topics/TopicForm.tsx

*In this PR, I migrated the components used in the create report page to MUI Material. This mostly involved replacing `Col` and `Row` with `Grid` and adapting the `Typography` from Ant Design to MUI. Also, the `MUI` tag was replaced with the `Chip`, and the buttons from `Ant Design` were replaced with `IconButton` because they are buttons that house icons.*
*In this PR, I managed to separate the pages as we discussed. The `Col` and `Row` were replaced by `Grid`, and in relation to this, the site's responsiveness needs to be tested. You can test the `Chip` by adding topics, while the `IconButton` tests the functionality and design of the buttons. All the Typography from Ant Design was also replaced, so it’s necessary to check if there is any text that’s out of the pattern or breaking the …

Migrate components used in the create report page to mui

---

src/components/Claim/ClaimView.tsx

*Basically, I set the initial value of the state to false, and in the useEffect, I performed a check on the size of the speech relative to the window size. If it was larger, it would mean the speech is scrollable and, therefore, the state would be set to true. Now, the default value is false, and it will only be set to true if the speech is scrollable.*
Fixes #1784 
*Go to the ClaimView page with a speech long enough to require scrolling the screen to read it entirely.*

Fixing the Toggle Section button

---

public/locales/en/history.json
public/locales/pt/history.json
src/components/Claim/ClaimList.tsx
src/components/Claim/ClaimListView.tsx
src/components/Claim/ClaimSourceList.tsx
src/components/Dashboard/DashboardView.tsx
src/components/Kanban/KanbanGrid.tsx
src/components/List/BaseList.tsx
src/components/Personality/PersonalityList.tsx
src/components/Skeleton/ClaimSkeleton.tsx
src/components/Skeleton/HistorySkeleton.tsx
src/components/Skeleton/KanbanSkeleton.tsx
src/components/Skeleton/ReviewCarouselSkeleton.tsx
src/components/Skeleton/SkeletonList.tsx
src/components/Skeleton/SourceSkeleton.tsx
src/components/Source/SourceList.tsx
src/components/Source/SourceListItem.style.tsx
src/components/Source/SourceListItem.tsx
src/components/history/HistoryListItem.tsx
src/components/history/HistoryView.tsx

*In this PR, I replaced the Ant Design `List` component used in `BaseList.tsx`. Since this component is used in several places, I had to make some adjustments where it was called. I preserved the old layout and design. Along the way, I also fixed some issues for smaller screen resolutions. In the documentation, you can see how the pages and their skeletons turned out.*
*To test, you would need to visit each of the components listed in the documentation and verify their responsiveness and behavior as a list. In some cases, I replaced Ant Design texts with Material-UI ones, but overall, the focus should be on testing the responsiveness of the listed pages.*
**Components:**
A visual document outlining which visual parts of the site need to be tested:  
[Testar BaseList e …

Migrating BaseList and its skeletons

---

src/components/Form/ClassificationModal.tsx

*ClassificationModal.tsx: Replace Antd Radio component with MUI Radio in ClassificationModal, add FormControlLabel to integrate custom labels (ClassificationText) with radio buttons, following MUI best practices.*
Fixes #1584 
*1. Be on mobile;
2. Log in to the platform;
3. Create a affirmation or open a existent;
4. Select the part of the affirmation you want to review;
5. Fill out the form;
6. Click in "Selecione uma Classificação" Select;
7. Click on the Radio to rate the sentence.*
Before:
After:

Migrate Radio Component in ClassificationModal

---

public/locales/en/verificationRequest.json
public/locales/pt/verificationRequest.json
src/components/VerificationRequest/CreateVerificationRequest/CreateVerificationRequestView.tsx
src/components/VerificationRequest/VerificationRequestAlert.tsx
src/components/VerificationRequest/VerificationRequestCard.tsx
src/components/VerificationRequest/VerificationRequestDisplay.style.tsx
src/components/VerificationRequest/VerificationRequestDisplay.tsx
src/components/VerificationRequest/VerificationRequestMainContent.tsx
src/components/VerificationRequest/VerificationRequestRecommendations.tsx
src/components/VerificationRequest/VerificationRequestResultList.tsx

*In this PR, I replaced some `Col`, `Row`, `Tag`, `Typography` in the page for creating `verification requests` and in the "verification request" page as well, following the patterns of previous changes. However, this was the first `Tag` I replaced, and the most accessible in the MUI library, which is the `Chip`. I adapted how to use them and kept the old design.*
*Basically, it was done with state management and DOM manipulation. First, I added ellipses via CSS to hide the rest of the text when it exceeds 3 lines if the condition is false. Then, I added the button with a function that would make the condition true, and in that way, set the line limit to 'none', displaying the full text.* 
*After that, I used a 'useEffect' with an 'if' statement and 'useRef' to check if the total content …

Migrate verification request page to mui material

---

src/components/AffixButton/AffixButton.tsx
src/components/AffixButton/AffixCTAButton.tsx
src/components/Form/ClassificationModal.tsx
src/components/ImageUpload.tsx
src/components/Modal/AletheiaModal.style.tsx
src/components/Modal/ModalButtons.tsx
src/components/Modal/OrderModal.tsx
src/components/Modal/ToolbarActionsModal.tsx
src/components/Modal/WarningModal.tsx
src/components/SentenceReport/Banner.style.tsx
src/components/SentenceReport/Banner.tsx

*In this PR, I migrated the component that creates a standard modal in the platform, which is used as the base for other modals. I adapted the Ant modal to the MUI dialog. This way, I replicated the design of the standard modal as much as possible and redesigned it where necessary in the places where the modal was called. In general, I used the dialog, migrated and adapted the buttons, and replaced some Col and Row with the grid. You can see in the documentation how it looks visually and the small design differences.*
*In this case, it would be necessary to test the responsiveness, functionality, and design of each modal in the documentation. Since I migrated a button that was used to cancel the modal, it would be necessary to specifically test the functionality of this button.* …

Migrating all modals to MUI

---

src/components/Form/ClaimReviewSelect.tsx
src/components/Header/SelectLanguage.tsx

*In this PR I changed two selects on the platform, the first was from the `ClaimReviewSelect.tsx` file, where the functionality is to select the classification of the section that is being reviewed, the second file is from `SelectLanguage.tsx`, it is a select to choose which language the user wants on the platform.*
Fixes #1583 #1592 
ClaimReviewSelect Test:
1. Be logged in to the platform;
2. Create a new affirmation or enter an affirmation that has not yet been reviewed;
3. Select the section to be reviewed;
4. Choose a reviewer;
5. The reviewer completes the form and uses select to select the review of the claim.
SelectLanguage Test:
1. Enter the platform; 
2. Click on the flag to select the language.
PDF DOCUMENT: …

Migrate Select Components

---

src/components/ContentWrapper.tsx
src/components/Footer/Footer.tsx
src/components/Header/Header.tsx
src/components/MainApp.tsx

*I replaced the Layout component from the library Ant Design for Material UI library, using the following components:*
*°Box*
*ºAppBar*
*ºGrid*
*In the MainApp arquive, i change the logic of rendering  CTA Button for better lecture and organization*
*1 - Open the Aletheia on your local and go to the main page, look at the Header (just change the Layout for AppBar)* 
*2 - then go all the way down on the same page and look at the content down the Header (change Layout for Box)*
*3 - Look the personalities and in the same page (change Layout and Row for Box and Grid)*
*4 - In the same page go all the way down and look the Footer (change Layout, Row and Col for Grid, Box and Typhograpy)*
*Just the layout component*
*Layout and another component*

Migrate antd to mui Layout component

---

src/components/Footer/AletheiaSocialMediaFooter.tsx
src/components/PartialReviewWarning.tsx
src/components/Personality/PersonalityCard.tsx
src/components/Personality/PersonalityCreateSearch.tsx
src/components/Personality/PersonalitySearchResultSection.tsx
src/components/Search/OverlaySearchResults.tsx
src/components/Search/SearchOverlay.tsx
src/stories/components/typography/Label.stories.tsx
src/stories/components/typography/Subtitle.stories.tsx

*In this one, I migrated a few remaining small components. Among them, I replaced Col, Row, Divider, Typography, and Form. These were easier adaptations, very similar to what I had done before. Specifically, for the Form, I only needed to adapt the way it calls the label inside it and replicate some styles with CSS.*
*To test these, the documentation will be very helpful. For the Form, you will test it in general by completing the forms on the pages I listed in the documentation and checking their responsiveness.*
**Components:**
A visual document outlining which visual parts of the site need to be tested:  
[Testes componentes variados (1).pdf](https://github.com/user-attachments/files/18509754/Testes.componentes.variados.1.pdf)
closes #1717 , closes #1767 , closes #1719 , closes #1741 , …

Migrating some small miscellaneous components

---

src/components/Form/InputSearch.tsx
src/components/Home/HomeHeader/HomeHeaderSearch.tsx
src/components/Personality/PersonalityCreateSearch.tsx
src/components/Search/OverlaySearchInput.tsx

*Changing the Antd Input to the MUI TextField which has the same functionality. In Ant Design, the prefix was added directly by prefix. In MUI, the correct approach is to use InputAdornment, ensuring that the icon is aligned with the input field.*
Fixes #1588 
*1. Log in to the platform;
2. Use the search field on the home page;
3. Access the personalities page;
4. Search for a personality in the search field in the header. *
[Migrate-inputSearch.pdf](https://github.com/user-attachments/files/18607407/Migrate-inputSearch.pdf)

Migrate InputSearch

---

src/components/Button.tsx

*Button.tsx: Replaced Ant Design's Button with Material-UI's Button in the project.*
Fixes #1505 
*1. Be logged into the platform;
2. Click on any button within the platform; and
3. See if you are redirected to the correct page that the button corresponds to.*

Migrate Button component from Antd to MUI

---

src/components/Footer/Footer.tsx
src/components/MainApp.tsx

*I made a mistake by not testing on scrollable pages and only tested on pages without scroll, not realizing that the footer was breaking. Essentially, it broke the layout on scrollable pages because the footer wasn't following the page's flow correctly.*
*To fix this, I removed the position: absolute from the footer and used alignSelf: "flex-end" to ensure that it always stays at the bottom of the layout. In the parent component, I added display: "grid" and minHeight: "100vh" to ensure that the structure occupies the full height of the screen.*
*Additionally, I wrapped the other components inside a Box, making sure they are treated as a single unit within the grid. This way, the elements stay grouped correctly without being stretched unexpectedly.*
fixes #1809 
before:
after:
*I am …

Fix Bug Footer

---

.gitmodules
config.example.yaml
deployment/config/config-file/modules/main.pkl
deployment/config/config-file/modules/ory.pkl
docker-compose.yaml
ory_config/hydra.yml
server/app.module.ts
server/auth/ability/abilities.guard.ts
server/auth/ability/ability.decorator.ts
server/auth/ability/ability.factory.ts
server/auth/base.guard.ts
server/auth/m2m-or-session.guard.ts
server/auth/m2m.guard.ts
server/auth/session.guard.ts
server/entities/m2m.entity.ts
server/entities/user.entity.ts

* Introduce a new M2M guard that will check if the request comes from another machine using OAuth2 backed by Ory hydra
* Refactor Guard logic and use a base guard to share utilities across guards
* Introduce a new ability called "Integration" that will have the ability to create entities in the platform, in the future we want more granularity through a scope based authentication
Links #1801 
You will need to setup Ory Hydra locally, use the docker-compose setup to enable such infrastructure:
```
docker compose up kratos kratos-migrate mongodb hydra hydra-migrate sqlite
```
You will need to manually create an OAuth2 client and generate the tokens through the hydra CLI:
```
docker exec aletheia-hydra-1 hydra create client --endpoint http://127.0.0.1:4445 --format json --grant-type …
```

 Implement M2M authentication using ory hydra

---

src/components/ClaimReview/ClaimReviewDrawer.tsx
src/components/ClaimReview/ReportModelButtons.tsx
src/components/ImageUpload.tsx

*In this PR, I simply changed the property name from `icon` to `startIcon` because `icon` alone does not work in MUI.*
Fixes #1822
before:
after:
before:
after:
before:
after:
*Verify that the icons are displayed correctly.*

Fix broken icons into buttons

---

src/machines/reviewTask/getNextEvent.ts

*Basically, these conditionals used to return an empty string, which was ignored when using the Ant Design button. However, after switching to the MUI button, they started rendering because MUI renders everything, including empty arrays, null, or false. I just had to ensure that none of these values were returned. I tested it in the fact-check report and all other sections, such such as verification requests and sources.*
Fixes #1812 
*Fact-check:*
*Informative news:*
*Test the different types of reports available on the platform, specifically in sentences.*

Fix extra button bug in report

---

src/components/Metrics/MetricsOverview.tsx
src/components/Metrics/ReviewProgress.tsx
src/components/Personality/PersonalityCard.tsx

*In this PR, I replaced the Progress component from Ant Design with MUI. Overall, I had to use a linear gradient for line progress and a circular progress for circles, as MUI does not unify them under a single component like Ant Design. To replicate the light gray background of the circular progress, I had to use two overlapping circles since it was not possible to define that element with CSS in MUI. In general, I managed to simplify some aspects while maintaining the design and responsiveness.*
*You may notice a color change in the progress components. This happens due to the library switch. To keep the previous, more vibrant, and lighter color, we would need to change the hexadecimal values in the constant where we define these colors or set a new constant with updated colors directly …

Migrate progress antd to MUI

---

.github/workflows/aws.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/nodejs.yml
src/components/Search/SearchResult.tsx

*SearchResults.tsx: Updated Grid container styles to prevent component breakage in mobile environments by setting flexWrap: "nowrap" to maintain elements on the same line and adding a 10px gap for consistent spacing.*
Fixes #1709 
*1. Be in a "small" environment with less than 768px, such as mobile;
2. Be logged in to the platform;
3. Enter the search page, if you are local http://localhost:3000/search;
4. Search for an existing personality.*
[Screencast from 18-02-2025 12:03:55.webm](https://github.com/user-attachments/assets/c11c96b0-6f57-44a5-a5f1-d32f68f09c21)

Fix Personality card break on smaller screens on search page 

---

.github/workflows/aws.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/nodejs.yml
src/components/BackButton.tsx

The following adjustments were made:
- Fixed the syntax of the step responsible for running component tests.
- Ensured that the cypress-run job includes both E2E and component tests.
- Adjustments to make sure the workflow is correctly identified and all tests are executed.
This change ensures that the CI/CD pipeline continues to function properly and that component tests are executed as expected.
Steps to validate the tests:
1. Ran the component tests locally using:
`yarn cypress run --component`
2. Verified that all tests passed without errors.
3. Pushed the changes to GitHub and monitored the execution in GitHub Actions.
4. Confirmed that the cypress-run job successfully executed the component tests.

Fix GitHub ACtions pipeline: ensure Cypress component tests run correctly

---

src/components/InputPassword.tsx
src/components/Login/SignUpForm.tsx
src/components/Profile/OryProfileView.tsx

*This PR was made to migrate InputPassword to the MUI library, where we changed the main `InputPassword.tsx` file and styled it in two files where it is called to change the styling, they are `SignUpForm.tsx` and `OryProfileView.tsx`.*
Fixes #1512 
*1. Log in to the platform;
2. Click on the avatar in the upper right corner;
3. Click on Log in or Register;
4. Test the password field;
5. Once logged in, to change the password, repeat the same process and click on My Account.*
Login Page
Before:
After:
Register Page
Before:
After:
Password Change Page
Before:
After:

Migrate InputPassword to MUI

---

src/components/Header/DonateButton.tsx
src/components/Personality/PersonalityCardButton.tsx
src/components/Source/SourceListItem.tsx
src/components/topics/TopicForm.tsx

*Fixed the text styling of the 'View Profile' buttons on the Personalities page and 'View Source' on the Repository page. All styling is now adjusted to avoid text wrapping on smaller screens.*
Fixes #1830 
*1. Log in to the platform;
2. Go to the Repository page;
3. Previously, the Access button source text was not centered in the center of the button;
4. Access it on smaller screens to see its responsiveness.*
Before: 
After:
1. Log in to the platform;
2. Go to the Personality page;
3. Previously, the text View the button profile was not centered in the center of the button on smaller screens;
4. Access it on smaller screens to see its responsiveness.
Before:
After:

Fix button text styling

---

src/components/Loading.tsx

*Basically, I centered the loading indicator relative to its parent div.*
Fixes #1845

Centralizing loading

---

src/components/Collaborative/Components/Source/EditorSouceList.style.tsx
src/components/Collaborative/Components/Source/EditorSourceList.tsx
src/components/Collaborative/Components/Source/EditorSourceListItem.tsx

*In this PR, I migrated the entire source editor used in the report to MUI. I used Grid instead of the List component because it is not very accessible for this type of dynamic list. I also migrated a Spin component from Ant Design, which has no direct equivalent in MUI, so I had to manually replicate it. Overall, I replicated everything exactly as it was before.*
Fixes #1561 #1562 
before:
after:
loading:
before:
[Screencast from 03-15-2025 06:06:18 PM.webm](https://github.com/user-attachments/assets/0a311c69-f779-428c-81c6-336516b59c00)
after:
[Screencast from 03-15-2025 06:05:30 PM.webm](https://github.com/user-attachments/assets/54d91d38-7f89-4c2f-b3c6-cf5269c73295)

Migrating editorSourceList to MUI

---

src/components/Claim/ClaimView.tsx
src/components/Collaborative/Components/AffixAletheiaButton.tsx
src/components/Collaborative/Components/AffixButtonV2.tsx
src/components/Collaborative/Components/AffixPreviewButton.tsx

*In this PR, I migrated the affix used in AffixPreviewButton.tsx and realized it was using the same logic I had already replicated for another affix. Therefore, I encapsulated the entire functionality into a new component and called it in both places.*
@thesocialdev 
*I noticed that when the affix is used in the report drawer, the functionality of keeping the affix with a fixed position when the screen is scrollable is not working. Should I create an issue for this?*
*The affix used in the report is behind a feature flag and is currently turned off because it wasn’t working. I will create an issue to resolve this as well.*
*Should I create two separate issues or combine them into one?*
Fixes #1558
In the speech:
In the report:
*To test the first affix, go to the claim page and test the …

Migrating affix to MUI

---

src/components/AletheiaMenu.tsx

*In this PR, I migrated the menu component from Ant Design to MUI's list. I did this because the menu was already housed within a drawer, so in the MUI menu, we wouldn't be using any specific properties from it. Therefore, it made more sense to use a list. You can see in this video testing all the sidebar buttons and their correct paths.*
https://github.com/user-attachments/assets/19a1c115-7729-42eb-b8a1-ed310fecbe0e
Fixes #1504    
*To test, you would need to go through each possible option in the sidebar and check if everything is leading to the correct path without errors.*

Migrating sidebar to MUI

---

src/components/Claim/CreateClaim/ClaimCreate.tsx
src/components/Form/DynamicInput.tsx
src/components/Modal/ToolbarActionsModal.tsx
src/components/TextArea.tsx

*In this PR, I migrated the textarea component from Ant Design (antd) to the MUI TextField. The main changes I made were adding the `multiline` property and setting the default initial style for the textarea in the CSS, including the `resize` property. This library change also resulted in a slight style difference — a line appears over the placeholder. I chose to keep this line because removing it via CSS would also remove the resize icon.*
Fixes #1524  
Speech creation page:  
https://github.com/user-attachments/assets/00faba26-6eba-4fc6-b8d1-fecda8ed3c38  
Crosschecking and hide speech modal:  
https://github.com/user-attachments/assets/37b50fe5-1822-4644-a3fc-fd9e66a27161
*To test it, go to the three places where this component is used: the speech creation page, the modal to hide a …

Migrating TextArea to MUI

---

src/components/About/About.tsx
src/components/AletheiaAlert.tsx
src/components/Login/OryLoginForm.tsx
src/components/Profile/OryProfileView.tsx

This PR migrates the `AletheiaAlert` component to MUI. I mainly had to adapt some elements that were previously being passed as props in Ant Design to be used as `children` in the MUI version. I also adjusted some styles to match the previous design, and there was a slight color change for the alert `type`.
You can see a full comparison of the alerts before and after the migration in this document:
[alert to MUI(2).pdf](https://github.com/user-attachments/files/19814647/alert.to.MUI.2.pdf)
color change:
before:
after:
Fixes #1479
To test it, you need to visit all pages where `AletheiaAlert` is used. It's easier to perform the tests by following the documentation provided in the PDF above.

Migrating aletheia alert to MUI

---

cypress/support/locators.ts
public/locales/pt/login.json
src/components/InputPassword.tsx
src/components/Label.tsx
src/components/Login/OryLoginForm.tsx
src/components/Login/SignUpForm.tsx
src/components/Profile/OryProfileView.style.tsx
src/components/Profile/OryProfileView.tsx
src/components/Profile/Totp.tsx
src/components/TextErrorForm.tsx

*In this PR, I migrated all Ant Design forms on the login, sign-up, and profile pages to React Hook Form. I also fixed some responsiveness issues. You can see more details in the attached Fluxes videos.*
Change password and login:
https://github.com/user-attachments/assets/006856f9-6a43-42d7-9afa-5dfb925060ef
Sign up before:
https://github.com/user-attachments/assets/6e0cb09e-5643-4982-81ff-1ce46085aac9
Sign up after:
https://github.com/user-attachments/assets/65d7dfce-6d36-487d-9e5f-aa37365fc142
Fixes #1689, Fixes #1761, Fixes #1762
*To test it properly, you need to go through the following flows on the platform:*
1. **Login flow** – Access the login page, submit correct and incorrect credentials, and check all validation and error messages.
2. **Sign-up flow** – Register a new user, …

Migrating form of login sign to react hook form

---

package.json
src/api/verificationRequestApi.ts

Changed the `GET /verification-request` endpoint to update the default sorting behavior for verification requests.
By default, results are now returned in descending (`desc`) order — meaning the most recent ones appear first.
Fixes #1448 
* Access the `/verification-request` route
* Verify that the returned data is sorted from the most recent to the oldest

Enhancement: Sort verification requests by newest first

---

src/components/topics/TopicForm.tsx

Replaced the `Autocomplete`, `FormControl`, `CircularProgress`, and `TextField` components from **MUI Joy** with their equivalents from **MUI Material** in the Sentence page.  
This change improves design consistency across the application and aligns the UI with the Material Design guidelines used elsewhere in the project.
Fixes #1773
1. Access the **Sentence** page.  
2. Verify that the replaced components render correctly using MUI Material styling.  
3. Test autocomplete behavior, form control layout, loading indicator, and text input.  
4. Check that all interactions (typing, selecting, submitting) still work as expected.  
5. Confirm that there are no visual regressions or layout issues.

Enhancement: Replace MUI Joy components with MUI Material on the sentence page
