AletheiaFact/aletheia

- .travis.yml
- docker-compose.yaml
Rebase and merge after [lint is fixed](https://www.pivotaltracker.com/story/show/161450238) and merged into master
> Fixing docker-compose and adding .travis.yml rules

- lib/util.js
@DuardoN a função createRouter segue o design pattern "Factory" então para manipular o objeto router e estender como um padrão para sempre que ele for criado, salve o novo objeto em uma variável, manipule e o retorne após finalizar todas as customizações.
> Adding properties to router after creating it

- packages/server/api/controller/personalityController.js
- packages/server/api/repository/personality.js
- packages/server/routes/personality.js
https://www.pivotaltracker.com/story/show/169429681
> Filter personality by name in the list endpoint

- README.md
Hi, @thesocialdev. I've added a README.md to the repository.
- Installation steps
- Nice title and description
- Added lerna badge like in [Tess](https://github.com/OpenTesseract/tess) repository
> Improvements for README

- package.json
- packages/front/package.json
- packages/front/yarn.lock
- packages/server/package.json
- packages/server/yarn.lock
- yarn.lock
- Use `resolutions` in package.json to resolve issues with packages that have become vulnerable
- Update yarn.lock
> fix: npm vulnerabilities

- packages/server/app.js
- packages/server/lib/wikidataResolver.js
- packages/server/package.json
- packages/server/server.js
- packages/server/yarn.lock
> Start using service-runner as the server framework

- packages/front/package.json
- packages/front/src/App.js
- packages/front/src/components/Personality/PersonalityCreate.jsx
- packages/front/yarn.lock
- packages/server/app.js
- packages/server/lib/wikidataResolver.js
- packages/server/package.json
- packages/server/routes/wikidata.js
- packages/server/server.js
- packages/server/yarn.lock
Page for personality creation
1) Use input search to search wikidata entity for given name
> Personality create

- packages/front/src/components/Personality/PersonalityList.jsx
This is the remainder task at https://www.pivotaltracker.com/story/show/161621424
> Add button to redirect user to Personality creation page

- packages/front/src/components/Claim/ClaimCreate.jsx
- packages/front/src/components/Claim/ClaimReview.jsx
- packages/front/src/components/Personality/PersonalityCreate.jsx
- packages/front/src/components/Personality/WikidataTypeAhead.jsx
- packages/front/src/index.js
- packages/server/lib/wikidataResolver.js
> Form feedback

- src/components/Personality/PersonalityCreate.jsx
PersonalityCreate is not sending wikidata id when creating the entity
> Fix profile pic missing. 

- src/App.js
Make footer stick to the bottom
> Footer UI behavior

- src/components/Form/AffixButton.jsx
- src/components/Personality/PersonalityList.jsx
- src/components/Personality/PersonalityView.jsx
> Add personality button

- server/api/controller/personalityController.ts
- server/api/repository/personality.ts
- server/routes/personality.js
Make personality data returned from getById consistent with listAll.
> make personality endpoints consistent

- src/App.js
Removing <a> tag
https://www.pivotaltracker.com/story/show/173178712
> Front | Header is clickable everywhere and refresh page

- server/routes/claimReview.js
- src/components/Claim/ClaimReview.jsx
- src/components/Form/ClaimReviewSelect.jsx
- src/i18n.js
1) Remove comments of old code for reCaptcha
2) Check for reCaptcha errors before adding a claimreview in the DB
3) i18n of the ClaimReview form
> Restore reCaptcha server and front

- src/components/Claim/ClaimCard.jsx
- src/components/Claim/ClaimCard.less
- src/components/Personality/PersonalityView.jsx
- src/components/Personality/PersonalityView.less
**Depends on https://github.com/OpenTesseract/aletheia/pull/123**
1) Render Claim content if available
2) CSS for ClaimCard comment box
> personality: ClaimCard content summary

- server/api/model/sourceModel.ts
- server/api/repository/claimReview.ts
- server/routes/source.ts
- src/components/Claim/ClaimReview.jsx
- src/i18n.js
**Depends on https://github.com/OpenTesseract/aletheia/pull/126**
1) When creating claim-review, also create a source if it exists
2) Finish ClaimReviewForm i18n
> claim-review: Submit source link to server

- tests/parser/parser.unit.ts
Parser test needed to be updated after schema changed.
> Fix parser test

- server/api/controller/personalityController.ts
- server/api/repository/personality.ts
- server/lib/wikidataResolver.js
- src/App.js
- src/api/personality.js
- src/components/Personality/NewPersonalityCreate.jsx
- src/components/Personality/PersonalityCard.jsx
- src/components/Personality/PersonalityCreateCTA.jsx
- src/components/Personality/PersonalityCreateForm.jsx
- src/components/Personality/PersonalityCreateSearch.jsx
- src/components/Personality/PersonalityList.jsx
- src/components/Personality/WikidataTypeAhead.jsx
- src/i18n.js
1) Improve Wikidata API search and merge results with Aletheia DB
existing personalities
2) If the personality is present in the search, create new personality
with a '+ add' button
3) Improve wikidata filtering, removing entries that don't belong to
instance of human
4) Separate personality create in form and search
5) Add call to action component to create personality when user don't find personality in search
6) Change WikidataTypeAhead behavior for new Personality Create Form
> personality: New Personality Create flow

- server/api/controller/personalityController.ts
- server/api/repository/personality.ts
- server/lib/wikidataResolver.js
- src/App.js
- src/api/personality.js
- src/components/Personality/NewPersonalityCreate.jsx
- src/components/Personality/PersonalityCard.jsx
- src/components/Personality/PersonalityCreateCTA.jsx
- src/components/Personality/PersonalityCreateForm.jsx
- src/components/Personality/PersonalityCreateSearch.jsx
- src/components/Personality/PersonalityList.jsx
- src/components/Personality/WikidataTypeAhead.jsx
- src/i18n.js
Depends on https://github.com/OpenTesseract/aletheia/pull/133
1) Add route
2) Add edit functionality to  PersonalityCreateForm
3) Clear fields button
4) i18n
> personality: Add edit mode to personality create

- server/lib/parser.ts
- tests/parser/parser.unit.ts
1) Lookup for Ph.D. words
2) Lookup for prefixes like Mr.
> parser: Improve parser coverage

- src/App.js
- src/App.less
- src/api/personality.js
- src/components/Claim/ClaimView.jsx
- src/components/Form/AffixButton.jsx
- src/components/Personality/PersonalityCard.jsx
- src/components/Personality/PersonalityCreateForm.jsx
- src/components/Personality/PersonalityList.jsx
- src/components/Personality/PersonalityView.jsx
- src/i18n.js
1) Claim View Metrics section header i18n
2) Make the app have a better look when in desktop mode
3) Remove ellipsizing of description
4) Loading in PersonalityList page
5) Remove AffixButton from PersonalityPage
6) Remove initial show for affix tooltip
7) Fix pagination handler
> cleaning up ui/ux before MVP launch

- src/components/Claim/ClaimCreate.jsx
- src/components/Claim/ClaimView.jsx
- src/components/Personality/PersonalityList.jsx
> Hotfix Claim creation

- package.json
- server/api/model/userModel.ts
- server/api/repository/user.ts
- server/app.js
- server/routes/user.ts
- src/App.js
- src/api/user.js
- src/components/Claim/ClaimReview.jsx
- src/components/Header/AletheiaHeader.jsx
- src/components/Login/LoginView.jsx
- src/components/Personality/PersonalityCreateSearch.jsx
- src/components/Personality/PersonalityList.jsx
- src/i18n.js
- src/index.js
- src/store.jsx
- yarn.lock
1) Tweak server to authenticate requests properly using cookies session
2) Create simple login page
3) Add user/validate endpoint to validate the user session
4) Refactor store reducer to include login state property alongside search
5) Implement client-side session validate when app is mounted
> Implement login and finish Login Page

- src/components/Personality/PersonalityCard.jsx
- src/components/Personality/PersonalityView.jsx
- src/components/ReviewStats.jsx
- src/i18n.js
1) Add new information to summarized card
2) merge summary information (review stats)
3) comply to UI vignette
4) i18n
> Merge summary information into Personality Card

- server/api/repository/claim.ts
- src/api/claim.js
- src/api/personality.js
- src/components/Claim/ClaimCard.jsx
- src/components/Claim/ClaimView.jsx
- src/components/Personality/PersonalityView.jsx
- src/components/ReviewStats.jsx
- src/constants/reviewColors.js
- src/i18n.js
1) Server: Sort claim reviews by count, to bring up the most reviewed
2) Create constants object for reviewed label colors. Apply it to ReviewStats
3) Move API calls to the API objects. Apply it to PersonalityView and clean-up unused code.
4) Finish UI according to vignette with i18n, proper API calls, and current data present in the Claim resource.
> 177234294/Claim Card

- package.json
- server/api/model/claimModel.ts
- server/app.js
- server/routes/claim.js
- server/routes/claimReview.js
- src/App.js
- src/api/claim.js
- src/components/Claim/ClaimCreate.css
- src/components/Claim/ClaimCreate.jsx
- src/i18n.js
- src/store.jsx
1) captcha validation
2) addition of new fields to the DB model and front-end form
3) UI/UX according to design vignette
4) add appropriate login guard
5) front: move claim server request logic to the api library
> 177334045: Finish Claim Create Form according to UI vignette

- nest/app.module.ts
- nest/claim-review/claim-review.module.ts
- nest/claim-review/claim-review.service.ts
- nest/claim-review/schemas/claim-review.schema.ts
- nest/claim/claim.module.ts
- nest/claim/claim.service.ts
- nest/claim/schemas/claim.schema.ts
- nest/main.ts
- nest/personality/personality.controller.ts
- nest/personality/personality.module.ts
- nest/personality/personality.service.ts
- nest/personality/schemas/personality.schema.ts
- nest/root/root.controller.ts
- nest/source/schemas/source.schema.ts
- nest/source/source.module.ts
- nest/stats/stats.controller.ts
- nest/stats/stats.module.ts
- nest/util.ts
- nest/wikidata/wikidata.module.ts
- server/routes/root.js
1. Add Personality, Claim, ClaimReview, Source models and register modules in the app
2. Migrate Personality logic to nest: routes, controller, repository, and util lib.
3. Migrate stats endpoint to nestjs
4. Update robots.txt and migrate health and robots.txt to nestjs
5. Load AppModule as Dynamic module and pass service-runner options
> Nest migration

- server/claim/claim.controller.ts
- server/personality/personality.controller.ts
- server/personality/personality.module.ts
- src/components/Claim/ClaimList.tsx
- src/components/Personality/PersonalityView.tsx
1) Fix nestjs view module import in personality module
2) Fix relative paths in nextjs, use always absolute
3) Fix claim list endpoint not querying with proper objectid
field
> personality page fixes

- server/claim/claim.controller.ts
- server/claim/claim.module.ts
- server/personality/personality.controller.ts
- src/api/personality.ts
- src/components/Claim/ClaimParagraph.tsx
- src/components/Claim/ClaimSentence.tsx
- src/components/Claim/ClaimView.tsx
- src/components/Form/InputSearch.tsx
- src/components/MainApp.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
- src/components/Personality/PersonalityView.tsx
- src/components/SearchOverlay.tsx
- src/pages/claim.tsx
- src/pages/personality-create-search.tsx
1) Restore functionality
2) Apply CSS from Figma prototype
3) Migrate ClaimView page to nextjs with SSR
> Migrate PersonalityCreateSearch page and ClaimView

- next-env.d.ts
- package.json
- server/app.module.ts
- server/main.ts
- server/personality/personality.controller.ts
- src/api/personality.ts
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
- yarn.lock
1) persist sessions
2) fix slug redirection on PersonalityCreateSearch
> introduce session persistence with mongo-connect

- public/locales/en/claimReviewForm.json
- public/locales/en/common.json
- public/locales/en/profile.json
- public/locales/en/sourceForm.json
- public/locales/pt/claimReviewForm.json
- public/locales/pt/common.json
- public/locales/pt/profile.json
- public/locales/pt/sourceForm.json
- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- server/claim/claim.module.ts
- server/claim/claim.service.ts
- server/claim/schemas/claim.schema.ts
- server/personality/schemas/personality.schema.ts
- src/components/Claim/ClaimCreate.tsx
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/Profile/ProfileView.tsx
- src/components/Source/SourceInput.tsx
1) Source form
2) API to save sources for Claim and ClaimReview
3) i18n
> Introduce sources input to Claim and ClaimReview forms

- package.json
- public/locales/en/claim.json
- public/locales/en/common.json
- public/locales/en/sourceForm.json
- public/locales/pt/claim.json
- public/locales/pt/common.json
- public/locales/pt/sourceForm.json
- server/personality/personality.service.ts
- server/users/users.controller.ts
- src/api/claim.ts
- src/api/stats.ts
- src/components/BackButton.tsx
- src/components/Claim/ClaimView.tsx
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/Source/SourceInput.tsx
- tests/api/claimReview.test.js
- yarn.lock
1) Introduce LinkPreview component to show sources
2) Finish Sources UI
> Add list of sources in ClaimView page

- src/components/AletheiaMenu.tsx
- src/components/BackButton.tsx
- src/components/Button.tsx
- src/components/Claim/ClaimCard.tsx
- src/components/Claim/ClaimCreate.tsx
- src/components/Claim/ClaimSentence.tsx
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/ClassificationText.tsx
- src/components/Header/HeaderContent.tsx
- src/components/Home/CTARegistration.tsx
- src/components/Home/Home.tsx
- src/components/LandingPage.tsx
- src/components/Login/LoginView.tsx
- src/components/MainApp.tsx
- src/components/Metrics/ReviewStats.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/Personality/PersonalityCreateCTA.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
- src/components/Profile/ProfileView.tsx
- src/components/SearchOverlay.tsx
- src/components/SocialMediaShare.tsx
- src/pages/about-page.tsx
- src/pages/landing-page.tsx
- src/pages/privacy-policy-page.tsx
- src/store/store.ts
> Fix vscode type warnings

- src/components/AletheiaSocialMediaFooter.tsx
- Replaced GitHub and LinkedIn urls in the footer component with the valid ones
- Click on  GitHub and LinkedIn icons in the footer of a page and check that it opens the correct page
Closes #280
> Fix social media urls

- src/components/Form/InputSearch.tsx
- src/components/HighlightedSearchText.tsx
- src/components/SearchOverlay.tsx
- Finish applying visual identity to search overlay component
Closes #289
> Finish UI: Searchbar overlay

- public/locales/en/personalityCTA.json
- public/locales/pt/personalityCTA.json
- src/components/Label.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
- src/components/Personality/PersonalitySearchResultSection.tsx
> Finish UI: Personality search page

- config.development.yaml
- config.production.yaml
- package.json
- server/app.module.ts
- yarn.lock
- Added an app-side rate limiter to not suffer from a DDOS attack simulation
> Add rate limiter in the application side

- server/home/home.controller.ts
- server/personality/personality.service.ts
quando atualiza rapidamente dá erros no wikidata ou isAllowedProp
> Add random list of personalities functionality at the home page

- package.json
- server/app.module.ts
- server/root/root.controller.ts
- server/sitemap/sitemap.controller.ts
- server/sitemap/sitemap.module.ts
- server/sitemap/sitemap.service.ts
- yarn.lock
-  Add a sitemap.xml endpoint and when hitting it the site will trigger the google sitemap API
Closes #306
> Generate sitemap#306

- server/app.module.ts
- server/claim/claim.controller.ts
- server/home/home.controller.ts
- server/main.ts
- server/middleware/language.middleware.ts
- server/personality/personality.controller.ts
- server/sitemap/sitemap.service.ts
- server/users/users.controller.ts
- server/view/view.controller.ts
- Refactoring code. Now we can get the language with middleware, which does the same thing as before, but with less code
> change the way we get the language using middleware (refactoring)

- src/components/Home/CTARegistration.tsx
> Added a tracker function on the CTA button #245

- server/claim-revision/claim-revision.service.ts
- server/claim-revision/schema/claim-revision.schema.ts
- server/claim/schemas/claim.schema.ts
> Restore relationship between claim and sources

- public/locales/en/history.json
- public/locales/pt/history.json
- server/claim/claim.controller.ts
- server/history/history.controller.ts
- server/history/history.module.ts
- server/history/history.service.ts
- server/personality/personality.controller.ts
- src/api/history.ts
- src/api/historyApi.ts
- src/components/List/BaseList.tsx
- src/components/LocalizedDate.tsx
- src/components/history/HistoryListItem.tsx
- src/components/history/HistoryView.tsx
- src/pages/history-page.tsx
Added pages to see the recent changes on a personality or claim
closes #326
> New History Pages

- server/personality/personality.service.ts
> fixed create a deleted personality error

- package.json
- public/locales/en/seo.json
- public/locales/pt/seo.json
- src/components/Home/CTARegistration.tsx
- src/components/Home/Home.tsx
- src/components/Login/LoginView.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/Personality/PersonalityList.tsx
- src/components/Personality/PersonalityView.tsx
- src/pages/_app.tsx
- src/pages/about-page.tsx
- src/pages/code-of-conduct-page.tsx
- src/pages/home-page.tsx
- src/pages/landing-page.tsx
- src/pages/login.tsx
- src/pages/privacy-policy-page.tsx
- yarn.lock
Start using Next Seo to add metatags like title and description to some pages and also add some h1 and alt tags on personality images.
The texts used are just placeholders for now.
> Start using next seo#307

- src/components/Home/Home.tsx
- src/components/Personality/PersonalityView.tsx
- src/pages/home-page.tsx
- src/pages/personality-page.tsx
When The User Is Logged:
When The User Is Not Logged:
> Set The Visibility Of Specific Buttons And Components Based On Login Authentication.  #354/#400

- server/app.module.ts
- server/middleware/logger.middleware.ts
> Creation Of a Logger Middleware.

- public/locales/en/seo.json
- public/locales/pt/seo.json
- src/components/ClaimReview/ClaimReviewCard.tsx
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/ClaimReview/ClaimSentenceCard.tsx
- src/pages/claim-review.tsx
> Improve html semantic in claim review page

- src/components/ClaimReview/ClaimReviewView.tsx
- src/pages/claim-review.tsx
> Enabled sharing in the claim review page #360

- public/locales/en/claim.json
- public/locales/en/claimForm.json
- public/locales/en/personality.json
- public/locales/pt/claim.json
- public/locales/pt/claimForm.json
- public/locales/pt/personality.json
- src/api/claim.ts
- src/api/ory.ts
- src/api/personality.ts
- src/components/Claim/ClaimCreate.tsx
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/lib/orysdk/errors.ts
> i18n server and client side #54

- server/claim-review/claim-review.service.ts
- src/api/claimReview.ts
- src/components/ClaimReview/ClaimReviewView.tsx
> Each sentence has only one review

- .github/workflows/gke.yml
- deployment.yml
- server/claim-review/claim-review.service.ts
- src/api/claimReview.ts
- src/components/ClaimReview/ClaimReviewView.tsx
[fixed create claim review bug error](https://github.com/AletheiaFact/aletheia/commit/39f25016926301d3f218b3987c2933801db90763)
[A sentence will only have one Claim Review](https://github.com/AletheiaFact/aletheia/commit/d72b85e64722f6af120f32f2e20c73dff025c9b0)
[Fix typo on gke.yml and deployment.yml that causes secret to not be applied](https://github.com/AletheiaFact/aletheia/commit/9d46a4dbaf9fc9ac7e7d2e9fdc0a91fba83cc930)
> Beta Cluster release

- .gitignore
Add file docker-compose.override.yaml in gitignore
> Add file docker-compose.override.yaml in .gitignore

- server/claim-review/claim-review.service.ts
- server/claim/claim.controller.ts
- server/report/report.controller.ts
- server/report/schemas/report.schema.ts
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/ClaimReview/form/DynamicForm.tsx
and fixed code smells from https://github.com/AletheiaFact/aletheia/pull/496
> Fixed machine bug when user is not logged in and try to access api

- cypress/integration/tests/home.spec.ts
- cypress/integration/tests/personality.spec.ts
- cypress/integration/tests/review.spec.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- cypress/support/locator.ts
- server/claim-review-task/claim-review-task.controller.ts
- server/claim-review-task/claim-review-task.module.ts
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review-task/dto/create-claim-review-task.dto.ts
- server/claim-review-task/dto/update-claim-review-task.dto.ts
- src/api/ClaimReviewTaskApi.ts
- src/components/AletheiaCaptcha.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/ClaimReview/form/DynamicForm.tsx
- src/machine/reviewTaskMachine.ts
- src/pages/claim-review.tsx
Adds reCaptcha validation to dynamic form in the workflow.
The reCaptcha is used for each action in the workflow and is reset after each form submission.
Closes #484
> Recaptcha in dynamic form#484

- src/api/ClaimReviewTaskApi.ts
- src/components/ClaimReview/form/DynamicForm.tsx
- src/machine/actions.ts
- src/machine/context.ts
- src/machine/events.ts
- src/machine/reviewTaskMachine.ts
- src/utils/ParseMachineState.ts
> Only show next form with api success #493

- .vscode/tasks.json
- next.config.js
- scripts/copyStaticAssets.ts
- src/components/Home/HomeCarousel.tsx
- Add Wikipedia domain to next.config.js
- Remove copy command with error from copyStaticAssets.ts
- Improve tasks.json
- Improvements on carousel and static background
> feat(Carousel): Finish MVP for personalities carousel

- .vscode/tasks.json
- cypress/integration/tests/review.spec.ts
- next.config.js
- scripts/copyStaticAssets.ts
- src/components/ClaimReview/UserAutocomplete.tsx
- src/components/ClaimReview/form/DynamicForm.tsx
- src/components/ClaimReview/form/DynamicInput.tsx
- src/components/Home/HomeCarousel.tsx
At the end of the form with the publishing event the reCAPTCHA does not appear.
> At the end of the form it does not show reCAPTCHA

- server/claim-review-task/claim-review-task.service.ts
- server/claim-review/claim-review.controller.ts
- server/claim-review/claim-review.service.ts
- src/api/claimReview.ts
- src/components/ClaimReview/form/DynamicForm.tsx
- src/machine/actions.ts
- src/machine/context.ts
- src/machine/events.ts
- src/machine/reviewTaskMachine.ts
we don't need to save utils in machine context 'cause we already has in event object. So i did code refactor
> Refactor machine context

- server/ory/ory.service.ts
- server/users/users.service.ts
> Fixed profile page error #500

- package.json
- src/components/Header/ButtonFlag.tsx
- src/components/Header/HeaderContent.tsx
- src/pages/404-page.tsx
- src/pages/about-page.tsx
- src/pages/claim-create.tsx
- src/pages/claim-page.tsx
- src/pages/claim-review.tsx
- src/pages/claim-sources-page.tsx
- src/pages/code-of-conduct-page.tsx
- src/pages/history-page.tsx
- src/pages/home-page.tsx
- src/pages/login.tsx
- src/pages/personality-create-search.tsx
- src/pages/personality-list.tsx
- src/pages/personality-page.tsx
- src/pages/privacy-policy-page.tsx
- src/pages/profile-page.tsx
- src/utils/GetLocale.ts
- yarn.lock
> Allow user to select language#373

- src/components/Button.tsx
- src/components/Home/CTARegistration.tsx
- src/components/Home/CTASection.tsx
Adjust Aletheia Button style in Registration CTA and CTA Section over the carousel where it should be rounded.
> Adjust button style where it should be rounded

- server/personality/dto/create-personality.dto.ts
- server/wikidata/wikidata.service.ts
- src/components/Personality/PersonalityCard.tsx
- src/components/SearchOverlay.tsx
> Improve performance for Personality images #552

- package.json
- server/app.module.ts
- server/jest.config.json
- server/tests/jest-e2e.config.json
- server/tests/mocks/SessionGuardMock.ts
- server/tests/personality.e2e.spec.ts
- server/tests/utils/SeedTestUser.ts
- server/tests/utils/TestConfigOptions.ts
- server/tests/utils/UserMock.ts
- server/view/view.module.ts
- server/view/view.service.ts
- yarn.lock
Starting with e2e tests for the personality creation endpoint
> Add support for e2e and unit tests

- src/components/AletheiaMenu.tsx
- src/components/Claim/ClaimCreate.tsx
- src/components/Login/OryLoginForm.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/Profile/OryProfileView.tsx
> Prevent double click action on api functions

- public/locales/en/NewCTARegistration.json
- public/locales/pt/NewCTARegistration.json
- src/components/ClaimReview/NewCTARegistration.tsx
- src/components/ClaimReview/SentenceReportCard.tsx
- src/components/ClaimReview/SentenceReportSummary.tsx
- src/components/ClaimReview/SentenceReportView.style.tsx
- src/components/ClaimReview/SentenceReportView.tsx
- src/components/ClaimReview/SetenceReportCard.style.tsx
- src/stories/components/buttons/SocialMediaShare.stories.tsx
- src/styles/colors.ts
Rewriting some properties to make the report page responsive
> Version mobile report page

- public/locales/en/profile.json
- public/locales/en/totp.json
- public/locales/pt/profile.json
- public/locales/pt/totp.json
- src/api/ory.ts
- src/components/AletheiaMenu.tsx
- src/components/Login/OryLoginForm.tsx
- src/components/Profile/OryProfileView.tsx
- src/components/Profile/Totp.tsx
- src/lib/orysdk/errors.ts
- src/lib/orysdk/utils.ts
> Two Factor Authentication with Ory

- src/components/Claim/ClaimCreate.tsx
- prevent selecting future dates
- disabled future dates
closes #576
> Prevent selecting a future date

- public/locales/en/home.json
- public/locales/pt/home.json
- src/components/Home/CTASection.tsx
- add umami analytics
- add direct link to the application form
- replace text
closes #572
> Update CTA Button on the home page

- public/locales/en/profile.json
- public/locales/pt/profile.json
- server/users/users.controller.ts
- src/api/ory.ts
- src/components/Profile/Totp.tsx
- src/lib/orysdk/errors.ts
> Change password working properly without a Privileged Session

- src/components/Claim/ClaimCreate.tsx
- src/components/Claim/ClaimView.tsx
- src/components/Home/HomeContent.style.tsx
- src/components/Personality/PersonalityCard.tsx
> fixed-personality-card-broken

- src/components/AletheiaMenu.tsx
- src/components/Sidebar.tsx
> Update Side Menu

- src/components/Button.tsx
- src/components/Home/CTARegistration.tsx
- src/components/Home/CTASection.tsx
- src/components/Personality/PersonalitiesGrid.tsx
Because `...props` when we pass rounded as prop returns a console error
> Fix rounded console error

- src/components/AletheiaInput.tsx
- src/components/Claim/ClaimCreate.tsx
- src/components/ClaimReview/form/DynamicInput.tsx
- src/components/ClaimReview/form/SelectUser.tsx
- src/components/Form/InputSearch.tsx
- src/components/InputPassword.tsx
- src/components/InputTextList.tsx
- src/components/TextArea.tsx
> Update Input components

- README.md
To use the TOTP functionality we need to enable it in ory console, so i updated the readme to make it possible for people to know how to enable it.
> Enable the TOTP on ory console

- server/claim-review-task/dto/create-claim-review-task.dto.ts
- server/claim-review/dto/create-claim-review.dto.ts
- server/report/report.service.ts
- server/report/schemas/report.schema.ts
- src/components/ClaimReview/form/DynamicForm.tsx
- src/machine/enums.ts
prevent undefined classification in create report function and in form data handling (DynamicForm)
closes #574
> Prevent undefined stats

- src/components/ClaimReview/ClaimSentenceCard.tsx
- src/components/ClaimReview/SentenceReportCard.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/SearchOverlay.tsx
- src/styles/colors.ts
> Update personality avatar component

- src/components/Home/HomeContent.tsx
- src/components/Personality/PersonalitiesGrid.tsx
> Fixed personality card broken#2

- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- server/claim/claim.controller.ts
- src/components/ClaimReview/SentenceReportView.tsx
- src/pages/sources-page.tsx
> Report Sources Page.

- public/locales/en/claimReviewTask.json
- public/locales/pt/claimReviewTask.json
- server/claim-review-task/claim-review-task.service.ts
- src/api/ClaimReviewTaskApi.ts
- src/components/ClaimReview/form/DynamicForm.tsx
- src/machine/enums.ts
- src/machine/reviewTaskMachine.ts
> Allow fact-checker to go back a step of the workfllow

- src/components/Button.tsx
- src/components/ClaimReview/NewCTARegistration.tsx
- src/components/ClaimReview/SentenceReportCard.tsx
- src/components/ClaimReview/SentenceReportContent.tsx
- src/components/ClaimReview/SentenceReportSummary.tsx
- src/components/ClaimReview/SentenceReportView.style.tsx
- src/components/ClaimReview/SentenceReportView.tsx
- src/components/ClaimReview/SetenceReportCard.style.tsx
- src/components/ClaimReview/form/DynamicInput.tsx
- src/components/Home/CTARegistration.tsx
- src/components/Home/CTASection.tsx
- src/components/InputTextList.tsx
> Fixed report page responsive

- cypress/integration/tests/review.spec.ts
- cypress/support/locators.ts
- public/locales/en/kanban.json
- public/locales/pt/kanban.json
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review-task/dto/create-claim-review-task.dto.ts
- server/claim-review/claim-review.controller.ts
- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- server/report/schemas/report.schema.ts
- src/api/ClaimReviewTaskApi.ts
- src/components/ClaimReview/form/SelectUser.tsx
- src/components/ClaimReview/form/unassignedForm.ts
- src/components/Kanban/KanbanCard.tsx
- src/machine/actions.ts
- src/machine/context.ts
- src/machine/events.ts
> Allow assigning multiple fact-checkers

- server/history/history.module.ts
- server/history/history.service.ts
> Analyze history schema

- src/components/Claim/ClaimView.tsx
- src/components/ClaimReview/NewCTARegistration.tsx
- src/components/ClaimReview/SentenceReportContent.tsx
- src/components/Footer/AletheiaSocialMediaFooter.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/FooterInfo.tsx
- src/components/Header/HeaderContent.tsx
- src/components/Home/CTARegistration.tsx
- src/components/Home/CTASection.tsx
- src/components/InfoAlert.tsx
- Adds rel="noreferrer" to external links
- Fix links on the header 
Closes #648
> Optimize links for seo

- server/auth/session.guard.ts
> Add config to make every page protected by login

- src/components/ClaimReview/form/DynamicForm.tsx
- src/components/ClaimReview/form/DynamicInput.tsx
- src/components/InputTextList.tsx
- src/components/SocialMediaShare.tsx
> Track clicks from fact checking workflow

- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- server/claim/claim.controller.ts
- src/pages/claim-review.tsx
- add date on review schema
- change the claim review publish date
closes #660
> Include claim review publish date on claim review schema

- src/components/Personality/PersonalityView.tsx
Added width 100% style for the component personality stats for mobile version.
> Added style for mobile version for Personality Stats

- dashboard/all-actions-in-fact-checking.js
- dashboard/average-fact-check-time.js
- dashboard/between-states.js
- dashboard/claim-started.js
- dashboard/fact-checking-started.js
> Dashboard queries

- src/components/Header/HeaderContent.tsx
- src/components/Header/SelectLanguage.tsx
- If the default_language cookie is not set, display the brazilian flag
- Remove the background and arrow icon from the select component 
Closes #637
> Display default flag if language cookie is not set

- src/components/AletheiaAvatar.tsx
- src/components/ClaimReview/ClaimSentenceCard.tsx
- src/components/ClaimReview/SentenceReportCard.style.tsx
- src/components/ClaimReview/SentenceReportCard.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/SearchOverlay.tsx
- src/components/SearchResult.tsx
- Create a component that wraps the avatar with the gray border
- Calculates the gap and thickness of the border based on the dimensions of the image
Closes #636
> Fix avatar border

- server/wikidata/wikidata.service.ts
> Fixed language of description when searching for personality.

- server/claim-review-task/claim-review-task.controller.ts
- server/claim-review-task/claim-review-task.module.ts
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review-task/mongo-utils.ts
- src/components/Kanban/KanbanCard.tsx
- src/components/Kanban/KanbanCol.tsx
- src/components/Kanban/UserTag.tsx
- Show sentence content as the title of the kanban
- Show avatars with the first letter of the users name on the card
Closes #582
> Improve kanban

- src/components/ClaimReview/TopicInput.tsx
- fixed delete more than one topic error
closes #532
> Fix delete more than one topic

- src/api/personality.ts
- src/components/AletheiaMenu.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/ClaimReview/ClaimSentenceCard.tsx
- src/components/ClaimReview/SentenceReportView.tsx
- src/components/ClaimReview/TopicInput.tsx
- src/components/ClaimReview/form/DynamicForm.tsx
- src/components/Header/HeaderContent.tsx
- src/components/Home/CTASection.tsx
- src/components/Home/Home.tsx
- src/components/Home/HomeCarousel.tsx
- src/components/Home/HomeContent.tsx
- src/components/MainApp.tsx
- src/components/Personality/PersonalitiesGrid.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
- src/components/Personality/PersonalityView.tsx
- src/components/SearchOverlay.tsx
- src/components/SocialMediaShare.tsx
- src/pages/claim-review.tsx
- src/pages/home-page.tsx
- src/pages/personality-page.tsx
- src/store/store.ts
- src/store/types.ts
- src/stories/components/buttons/SocialMediaShare.stories.tsx
- The pages where we need to know if the user isLoggedIn dispatch an action that saves this value in the redux store and the component that need the value can access it without having to pass it as a prop.
> Use redux to access isLoggedIn value

- server/middleware/language.middleware.ts
- server/personality/personality.service.ts
> Description Translation

- cypress/integration/tests/review.spec.ts
- cypress/support/locators.ts
- public/locales/en/orderModal.json
- public/locales/en/tutorial.json
- public/locales/pt/orderModal.json
- public/locales/pt/tutorial.json
- src/components/Form/AffixButton.tsx
- src/components/Modal/AletheiaModal.style.tsx
- src/components/Modal/OrderModal.tsx
- src/components/PulseAnimation.tsx
- src/components/Radio/OrderRadio.tsx
- Add a modal and animation showing the button to create a speech
- The modal and button only appear for logged in users
- After dismiss the modal or click the button to create a speech, set a cookie to not show the modal again
https://user-images.githubusercontent.com/8875518/186896322-c08e479b-08cc-406f-b2ef-509092819ad0.mp4
Closes #694
> Add a tutorial to the create speech button

- src/components/ClaimReview/TagsList.tsx
- src/components/ClaimReview/TopicInput.tsx
- fixed i18n
- when topics doesn't exist show add icon
closes #715
> Include Add Topics Icon

- src/components/Claim/ClaimView.tsx
- src/components/Home/Home.tsx
- src/components/List/BaseList.tsx
- src/components/Loading.tsx
- src/components/Login/LoginView.tsx
- src/components/Login/OryLoginForm.tsx
- src/components/Personality/PersonalityCard.tsx
- src/components/Personality/PersonalityView.tsx
- src/components/Profile/OryProfileView.tsx
- src/components/Skeleton/PersonalitySkeleton.tsx
- Create a Loading component that complies to the visual identity and use it on page loading instead of the default spin.
Closes #590
> Apply visual identity on page loading

- cypress/integration/tests/personality.spec.ts
- cypress/integration/tests/review.spec.ts
- cypress/support/commands.ts
- cypress/support/locators.ts
- public/locales/en/affix.json
- public/locales/en/personality.json
- public/locales/en/tutorial.json
- public/locales/pt/affix.json
- public/locales/pt/personality.json
- public/locales/pt/tutorial.json
- src/components/AffixButton/AffixButton.tsx
- src/components/AffixButton/Fab.tsx
- src/components/Personality/PersonalityView.tsx
- src/pages/claim-create.tsx
- src/pages/claim-page.tsx
- src/pages/claim-review.tsx
- src/pages/home-page.tsx
- src/pages/kanban-page.tsx
- src/pages/personality-list.tsx
- src/pages/personality-page.tsx
- src/stories/components/buttons/AffixButton.stories.tsx
- Added the Create Personality option to the floating button 
- Show the floating button on more pages
- On the pages where a personality is available, the floating button will have the options to create personality or claim
Closes #695
> Improve floating button

- src/components/Form/ClaimReviewSelect.tsx
- src/components/Form/ClassificationModal.tsx
- src/components/Header/SelectLanguage.tsx
- src/components/Modal/AletheiaModal.style.tsx
Version Mobile
Language Select 
closes #534
> Update classification input

- public/locales/en/topics.json
- public/locales/pt/topics.json
- src/components/ClaimReview/TopicInput.tsx
> Checking duplicated topics in the sentence.

- src/components/AletheiaCaptcha.tsx
- src/components/Claim/ClaimCreate.tsx
- src/components/ClaimReview/form/DynamicForm.tsx
- src/components/Modal/HideReviewModal.tsx
- src/components/Modal/UnhideReviewModal.tsx
> Text feedback for captcha requirement.

- public/locales/en/videoCard.json
- public/locales/pt/videoCard.json
- src/components/AletheiaVideo.tsx
- src/components/Home/HomeHeader.style.tsx
- src/components/Home/HomeHeader.tsx
- src/components/VideoCTACard.tsx
> Video Card Creation

- package.json
- server/claim-review-task/claim-review-task.service.ts
- server/types/BaseRequest.ts
- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/ClaimReview/ClaimReviewHeader.tsx
- src/components/SentenceReport/SentenceReportContent.tsx
- src/components/SentenceReport/SentenceReportView.tsx
- yarn.lock
- Users with the admin role can access the workflow at any state and change the contents of the forms before the review is published.
Closes #766 
Closes #767
> Admin users can access the workflow at any state

- src/components/ClaimReview/ClaimReviewDrawer.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/pages/claim-review.tsx
Enables social media sharing from the Claim Review Drawer.
> Social media sharing in the Claim Review Drawer

- server/claim-revision/schema/claim-revision.schema.ts
- server/claim/claim.controller.ts
- server/claim/claim.service.ts
- server/paragraph/schemas/paragraph.schema.ts
- server/personality/personality.service.ts
- server/speech/schemas/speech.schema.ts
- adds auto populate on paragraph.content, speech.content and claimRevision.content 
- Cleans some TODOs and code smells
> Auto populate speech content using pre hook

- public/locales/en/unauthorized.json
- public/locales/pt/unauthorized.json
- server/ability/abilities.guard.ts
- server/app.module.ts
- server/filters/not-found.filter.ts
- server/filters/unauthorized.filter.ts
- server/view/view.controller.ts
- src/components/AcessDeniedPage.tsx
- src/pages/acess-denied-page.tsx
> Unauthorized page for UnauthorizedExption

- server/claim/claim.controller.ts
- src/components/Claim/CreateClaim/ClaimUploadImage.tsx
The recaptcha will be necessary to enable the button and validated on the backend
> Add recaptcha requirement to upload images

- public/locales/en/claim.json
- public/locales/pt/claim.json
- server/claim-revision/claim-revision.service.ts
- server/file-management/file-management.controller.ts
- server/file-management/file-management.module.ts
- server/image/image.controller.ts
- server/image/image.module.ts
- src/api/image.ts
- src/components/Claim/CreateClaim/ClaimUploadImage.tsx
Send a status 303 when trying to upload an image that already exists in the platform. 
Closes #815
> Stop users from uploading the same file multiple times

- .github/workflows/gke.yml
- config.development.yaml
- config.example.yaml
- config.production.yaml
- config.test.ci.yaml
- server/file-management/file-management.module.ts
- server/file-management/file-management.service.ts
- src/components/SentenceReport/Banner.tsx
- src/components/SentenceReport/SentenceReportCard.tsx
Fix bugs found in the test environment
- the link to see the full speech
- the link to sign up on the report page
- the aws variables that were not defined properly;
> fix: links and aws variables

- config.development.yaml
- config.example.yaml
- config.production.yaml
- config.test.ci.yaml
- src/components/SentenceReport/Banner.tsx
> fix: use of aws endpoint in config files

- src/components/AffixButton/AffixButton.tsx
> Checking user role to display AffixButton with and whitouth create claim option.

- server/personality/personality.service.ts
> Changed find query to fix personality search when the name of personality is misspelled

- src/components/Claim/CreateClaim/ClaimSelectPersonality.tsx
- src/machines/createClaim/createClaimMachine.ts
> Prevented user to create claim without a personality and fixed remove personality button.

- server/claim-revision/schema/claim-revision.schema.ts
- server/image/schemas/image.schema.ts
- server/types/enums.ts
> Using correct default prop on Image Schema to match ContentEnum.

- server/debate/debate.service.ts
- server/debate/schemas/debate.schema.ts
> Added createdAt and updatedAt on Debates

- src/components/SentenceReport/SentenceReportCard.tsx
Closes #836
Correction of the first topic on the issue the two others were already fixed on: #801 and #840.
> Fix:Fixed path for see full speech

- server/badge/badge.controller.ts
- src/atoms/editDrawer.ts
- src/components/badges/BadgesFormDrawer.tsx
> BugFix:  Badge Form Update

- server/auth/ory/ory.service.ts
- server/users/users.controller.ts
- server/users/users.service.ts
- src/components/adminArea/UserEditDrawer.tsx
> Fixing user role create and update on Ory and BugFix on UserEditDrawer.

- public/locales/en/profile.json
- public/locales/pt/profile.json
- src/components/Profile/OryProfileView.tsx
> Added title for badges section on profile.

- src/components/SourcesList.style.tsx
- src/components/SourcesList.tsx
> Removed react-link-preview and simplified sources section.

- server/claim/types/image/image.controller.ts
- server/claim/types/image/image.module.ts
- server/claim/types/image/image.service.ts
- server/claim/types/image/schemas/image.schema.ts
- server/claim/types/sentence/sentence.controller.ts
- server/topic/topic.module.ts
- server/topic/topic.service.ts
- src/api/image.ts
- src/api/sentenceApi.ts
- src/components/Claim/ClaimParagraph.tsx
- src/components/Claim/ClaimView.tsx
- src/components/ClaimReview/ClaimReviewHeader.tsx
- src/components/ClaimReview/TopicInput.tsx
- src/components/Form/Autocomplete.tsx
- src/components/Form/SelectOptions.tsx
- Fixed CRUD topics on image and speech claim types
- Avoid search same topic
- Bring latest topics on open drawer reviewer
- Reflect topic input on remove a tag
closes #894
closes #849
> Fixed and enhancement CRUD topics

- server/personality/schemas/personality.schema.ts
correct field name
closes #898
> Fixed personality stats

- src/components/Metrics/ReviewStats.tsx
Fixed review stats component show all reviews functionality
closes #896
> Fixed review stats component

- public/locales/en/profile.json
- public/locales/pt/profile.json
- src/components/Profile/OryProfileView.tsx
> Added Placeholder For Empty Badges on Profile.

- src/api/ory.ts
- src/components/Login/LoginView.tsx
- src/pages/login.tsx
Checks if user came from an external page and defines router proper action.
closes #843
> Login redirect 843

- server/claim/claim.controller.ts
> Restore recaptcha validation on create a claim

- src/components/Editor/Editor.tsx
- src/components/Editor/EditorClaimCard/EditorClaimCard.tsx
- src/pages/debate-editor.tsx
save personality and claim data in redux store
closes #901
> Fixed bug infinite loading edit mode

- server/home/home.controller.ts
> Only show live debates in home page

- server/filters/not-found.filter.ts
> Improved Logging on not-found.filter

- src/components/ClaimReview/ClaimReviewDrawer.tsx
- src/components/ClaimReview/ReviewsCarousel.tsx
> Loading feedbacks when changing to report page

- server/claim/claim-revision/claim-revision.service.ts
- server/claim/types/sentence/sentence.service.ts
- server/personality/personality.service.ts
- server/search/search.controller.ts
- server/search/search.module.ts
- src/api/searchApi.ts
- src/components/ContentWrapper.tsx
- src/components/Search/AutoCompleteList.tsx
- src/components/Search/PaginationOptions.tsx
- src/components/Search/SearchCard.tsx
- src/components/Search/SearchPageView.tsx
- src/components/Search/SearchResult.tsx
- src/pages/search-page.tsx
- src/store/store.ts
- src/store/types.ts
> Search Page

- public/locales/en/search.json
- public/locales/pt/search.json
- server/claim/claim-revision/claim-revision.service.ts
- server/claim/types/sentence/sentence.service.ts
- server/personality/personality.service.ts
- server/search/search.controller.ts
- server/topic/topic.controller.ts
- src/api/topicsApi.ts
- src/components/ClaimReview/TagsList.tsx
- src/components/ClaimReview/TopicInput.tsx
- src/components/Search/AdvancedSearch.tsx
- src/components/Search/AutoCompleteList.tsx
- src/components/Search/PaginationOptions.tsx
- src/components/Search/SearchPageView.tsx
- src/pages/search-page.tsx
- src/store/store.ts
- src/store/types.ts
- Manage filter query parameter and adapted functions to make it possible search with and without filter parameters
- Adapted Sentence findAll to be able to search by filter without necessary a searchText
- Create a Advanced Search Component to manage filters on the search
- Made topic tags clickable redirecting user to search page with the tag as the main filter
> Search Page With Filters:

- server/personality/dto/get-personalities.dto.ts
- server/personality/personality.controller.ts
- src/api/personality.ts
- src/components/Personality/PersonalityCard.tsx
- src/components/Personality/PersonalityCreateSearch.tsx
> Fixed Behavior of Add and Select Button.

- public/locales/en/warningModal.json
- public/locales/pt/warningModal.json
- src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
- src/components/Modal/AletheiaModal.style.tsx
- src/components/Modal/WarningModal.tsx
- src/styles/colors.ts
> Create goback warning modal

- server/claim-review-task/claim-review-task.service.ts
> Fixed order button

- server/claim/claim.service.ts
> Fixed image-claims-page

- server/claim/types/sentence/sentence.controller.ts
> change sentence route to public

- server/personality/dto/create-personality.dto.ts
> Fixed personality creation with twitter account

- server/claim/types/sentence/sentence.controller.ts
- server/personality/dto/create-personality.dto.ts
[Fixed personality creation with twitter account #971](https://github.com/AletheiaFact/aletheia/pull/971)
> Beta Cluster release: Fixed personality creation with twitter account #971

- public/locales/en/claimReviewTask.json
- public/locales/pt/claimReviewTask.json
- server/claim-review-task/claim-review-task.service.ts
- server/claim/claim.service.ts
- src/components/Claim/ClaimSentence.tsx
- src/components/Claim/SentencePopover.tsx
- src/constants/highlightColors.js
> Highlighted sentences those are being checked

- cypress.config.ts
- cypress/e2e/tests/header.cy.ts
- cypress/e2e/tests/personality.cy.ts
- cypress/support/commands.ts
- src/components/Header/UserMenu.tsx
- Increase timeout
- Fix header broken tests
- Fix personality tests and skip the image creation one
> Fix Cypress Tests

- server/users/users.controller.ts
- server/users/users.service.ts
- src/api/userApi.ts
- src/components/Header/UserMenu.style.tsx
- src/components/Header/UserMenu.tsx
- src/components/Home/CTAButton.tsx
- change antd Menu due deprecated property
- use mui Menu
- prevent route errors
> Change Menu library due deprecated warning

- src/components/Collaborative/CollaborativeEditorProvider.tsx
- only create websocket connection when colllab edit feature flag is enabled
> Fixed websocket connection console errors

- server/logger.ts
> Stopped logging Feature flag debug #932

- server/personality/personality.controller.ts
- server/personality/personality.service.ts
> Fixed More Personalities Component

- server/claim-review-task/claim-review-task.service.ts
- server/claim-review/claim-review.service.ts
- server/mongo-pipelines/lookUpPersonalityties.ts
- server/mongo-pipelines/lookupClaimRevisions.ts
- server/mongo-pipelines/lookupClaims.ts
- src/components/Skeleton/ReviewCarouselSkeleton.tsx
- modify lookup pipelines
- filter review that has hidden personality or claims
closes #993
> Don't show the latest reviews that have a hidden personality or claim

- src/components/AletheiaMenu.tsx
- Make kanban menu item only visible for fact-cheker or higher roles
- fixed admin menu items
- rearrange menu items
> Fixed menu items roles check

- src/components/AletheiaMenu.tsx
- src/components/Header/DonateButton.tsx
- src/components/Header/HeaderActions.style.tsx
- src/components/Header/HeaderContent.tsx
- src/components/Header/SelectLanguage.tsx
- src/components/Header/UserMenu.tsx
- src/components/Notification/NotificationIcon.tsx
- src/components/Notification/NotificationMenu.tsx
- src/components/Search/SearchOverlay.tsx
- only shows donate button when user is logged in
- change notification menu style
- aligned items correctly
> Fixed header responsive desing

- public/locales/en/claim.json
- public/locales/en/personality.json
- server/auth/session.guard.ts
- server/claim-review/claim-review.controller.ts
- server/claim-review/claim-review.service.ts
- server/claim/claim.service.ts
- server/personality/personality.service.ts
- server/stats/stats.service.ts
- src/components/ClaimReview/ClaimReviewView.tsx
- src/pages/personality-page.tsx
- Typos in i18n
- Hide and Delete queries
- Super Admin role check not working properly in personality page
> General bug fixes

- public/locales/en/login.json
- public/locales/pt/login.json
- src/components/Login/ForgotPasswordLink.tsx
- src/components/Login/OryLoginForm.tsx
> Recovery Account

- lib/editor-parser.ts
- migrations/20231013183353-move-source-extra-properties.ts
- src/components/Collaborative/CollaborativeEditorProvider.tsx
- src/components/Form/DynamicInput.tsx
[Fixed empty collaborative editor content bug #1055](https://github.com/AletheiaFact/aletheia/pull/1055)
[Production Hotfix: Made editor-parser function flexible from different schemas #1056](https://github.com/AletheiaFact/aletheia/pull/1056)
> Production Hotfix: backwards compatibility for claim task old schemas

- server/badge/badge.controller.ts
- server/badge/badge.module.ts
- server/claim/claim.controller.ts
- server/personality/personality.controller.ts
- server/personality/personality.module.ts
- server/tests/personality.e2e.spec.ts
> Enhanced RBAC For Public Routes.

- server/app.module.ts
- server/claim-review-task/claim-review-task.controller.ts
- server/claim-review-task/claim-review-task.module.ts
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review-task/comment/comment.controller.ts
- server/claim-review-task/comment/comment.module.ts
- server/claim-review-task/comment/comment.service.ts
- server/claim-review-task/comment/schema/comment.schema.ts
- server/claim-review-task/dto/create-claim-review-task.dto.ts
- src/api/ClaimReviewTaskApi.ts
- src/api/comment.ts
- src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
- src/components/ClaimReview/form/fieldLists/submittedForm.ts
- src/components/Collaborative/CollaborativeEditor.style.tsx
- src/components/Collaborative/CollaborativeEditor.tsx
- src/components/Collaborative/CollaborativeEditorProvider.tsx
- src/components/Collaborative/Comment/CommentCard.style.tsx
- src/components/Collaborative/Comment/CommentCard.tsx
- src/components/Collaborative/Comment/CommentCardActions.tsx
- src/components/Collaborative/Comment/CommentCardContent.tsx
- src/components/Collaborative/Comment/CommentCardForm.tsx
- src/components/Collaborative/Comment/CommentCardHeader.tsx
- src/components/Collaborative/Comment/CommentContainer.tsx
- src/components/Collaborative/Comment/CommentPopoverContent.tsx
- src/components/Collaborative/Comment/CommentsList.tsx
- src/components/Collaborative/Components/Source/EditorSouceList.style.tsx
- src/components/Collaborative/Editor.tsx
- src/components/Collaborative/Form/QuestionCard.tsx
- src/components/SentenceReport/SentenceReportView.tsx
- src/machines/reviewTask/getNextForm.ts
> MVP Review comments

- server/users/users.service.ts
- src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
> Do not show publish button for fact-checkers during cross-checking

- server/wikidata/wikidata.service.ts
- src/components/Personality/PersonalityCreateSearch.tsx
> Allow personalities to be public companies

- server/badge/badge.controller.ts
- server/users/users.service.ts
- src/components/adminArea/AdminView.tsx
- src/components/badges/BadgesView.tsx
> Fixed badges CRUD

- server/personality/dto/create-personality.dto.ts
- server/wikidata/wikidata.service.ts
> Allow personality to be online newspaper

- src/components/MainApp.tsx
- src/pages/_app.tsx
> Fixed ory whoami request every time on sidebar click

- server/claim-review-task/mongo-utils.ts
- src/components/Kanban/KanbanCol.tsx
- src/components/Kanban/KanbanView.tsx
> Create kanban cross-checking column

- server/claim-review-task/claim-review-task.controller.ts
- server/claim/claim.controller.ts
- src/components/Collaborative/CollaborativeEditor.tsx
- src/components/Collaborative/Comment/CommentCard.tsx
- src/components/Collaborative/Comment/CommentCardActions.tsx
- src/components/Collaborative/Comment/CommentCardContent.tsx
- src/components/Collaborative/Comment/CommentCardForm.tsx
- src/components/Collaborative/Comment/CommentContainer.tsx
- src/pages/claim-page.tsx
- src/pages/claim-review.tsx
- src/pages/kanban-page.tsx
- src/store/store.ts
- src/store/types.ts
> Enabled Editor Annotations by Feature Flag

- .github/workflows/nodejs.yml
- .gitignore
- cypress/e2e/tests/personality.cy.ts
- cypress/fixtures/user.ts
- server/claim/claim.controller.ts
- server/claim/dto/create-claim.dto.ts
create env variable for user password and replace it on CI jobs run
> Fixed Cypress CI Tests

- src/components/Collaborative/Comment/CommentCard.tsx
- src/components/Collaborative/Comment/CommentContainer.tsx
- src/components/Form/UserInput.tsx
- src/components/Notification/NotificationCard.tsx
- Fixed cross-checking comments card click
- Fixed disappearance of crossChecking comments after report change
- Fixed default value to prevent old claim review tasks cross-checking error
- remove console.log
> HOTFIX: Features releases errors

- server/auth/name-space/name-space.service.ts
- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- src/api/claimReviewApi.ts
We are not ready for this yet. The test environment is failing to open the claim review forms.
> Revert "Replace MongoDB Lookup to mongoose populate"

- server/seed.ts
- server/users/dto/get-users.dto.ts
- server/users/users.controller.ts
- server/users/users.service.ts
- src/api/userApi.ts
- src/components/ClaimReview/form/fieldLists/unassignedForm.ts
- src/components/Form/FormField.ts
- src/components/Form/SelectOptions.tsx
> Enforce fact-checkers to only assign themselves when starting a fact-checking

- server/claim-review/claim-review.module.ts
- server/claim-review/claim-review.service.ts
- server/claim/claim.controller.ts
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/SentenceReport/SentenceReportContent.tsx
- src/components/SentenceReport/SentenceReportView.tsx
- src/components/Source/SourcesList.tsx
- Fixed editor content html not working on claim review drawer
- Only show `see more sources` button when report is published
- Sort sources list
> Fixed sentence report view bugs

- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/ClaimReview/ClaimReviewHeader.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/SentenceReport/SentenceReportCard.style.tsx
- src/components/SentenceReport/SentenceReportCard.tsx
- src/components/SentenceReport/SentenceReportView.tsx
> Fixed claim review header responsive card

- src/components/ClaimReview/ClaimReviewForm.tsx
- src/components/ClaimReview/ClaimReviewView.tsx
- src/components/Collaborative/hooks/useFloatingLinkState.tsx
- fixed start review buttons responsivity
- only show claimReviewTaskAdminToolbar when task has started
- fixed floatingLinkToolBar selection
> Fix a few bugs for Production release 1.0.1

- server/auth/name-space/name-space.module.ts
- server/auth/name-space/name-space.service.ts
- server/claim-review/claim-review.service.ts
- server/notifications/notification.controller.ts
- server/notifications/notifications.module.ts
- server/notifications/notifications.service.ts
- server/summarization/summarization-chain.service.ts
- server/summarization/summarization.controller.ts
- server/summarization/summarization.module.ts
- server/summarization/summarization.service.ts
- src/api/notificationsApi.ts
> Daily Reviews Report

- config.development.yaml
- config.example.yaml
- config.production.yaml
- config.seed.example.yaml
- public/locales/en/notification.json
- public/locales/pt/notification.json
- server/auth/name-space/name-space.service.ts
- server/claim-review/claim-review.service.ts
- server/notifications/notification.controller.ts
- server/notifications/notifications.service.ts
- server/summarization/summarization.controller.ts
- server/summarization/summarization.service.ts
- src/api/notificationsApi.ts
- src/components/namespace/NameSpaceFormDrawer.tsx
> Daily Report Sender on the Platform.

- server/summarization/summarization.service.ts
> Enhance daily report design

- server/claim/claim-revision/claim-revision.service.ts
- server/claim/claim.controller.ts
- server/claim/claim.service.ts
> Fixed claim without personality routes

- public/locales/en/notification.json
- public/locales/pt/notification.json
- server/summarization/summarization.service.ts
> Send custom message when daily report is empty

- public/locales/en/claimReviewForm.json
- public/locales/pt/claim.json
- public/locales/pt/claimReviewForm.json
- public/locales/pt/menu.json
- server/copilot/copilot-chat.service.ts
- server/daily-report/daily-report.controller.ts
- server/daily-report/daily-report.service.ts
- server/daily-report/schemas/daily-report.schema.ts
- server/summarization/summarization-chain.service.ts
- server/summarization/summarization.service.ts
- Instead redirect users to aletheia claim review page, redirect them to the fact-checking report url
- Improve user experience labels
> HOTFIX: Daily report feature

- migrations/20240603163246-add-namespace-fiel-on-claim-review-schema.ts
- public/locales/en/claimReviewForm.json
- public/locales/pt/claim.json
- public/locales/pt/claimReviewForm.json
- public/locales/pt/menu.json
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review/claim-review.controller.ts
- server/claim-review/claim-review.service.ts
- server/claim-review/schemas/claim-review.schema.ts
- server/copilot/copilot-chat.service.ts
- server/daily-report/daily-report.controller.ts
- server/daily-report/daily-report.service.ts
- server/daily-report/schemas/daily-report.schema.ts
- server/personality/personality.service.ts
- server/stats/stats.service.ts
- server/summarization/summarization-chain.service.ts
- server/summarization/summarization.service.ts
- server/tests/utils/ClaimReviewMock.ts
> Add namespace to claim review schema

- cypress/e2e/tests/review.cy.ts
- cypress/support/locators.ts
- lib/editor-parser.ts
- public/locales/en/sourceForm.json
- public/locales/pt/sourceForm.json
- server/claim-review-task/claim-review-task.controller.ts
- server/claim/claim.controller.ts
- src/components/ClaimReview/form/DynamicReviewTaskForm.tsx
- src/components/Collaborative/CollaborativeEditor.tsx
- src/components/Collaborative/Components/LinkToolBar/Dialog/SourceDialog.tsx
- src/components/Collaborative/Components/LinkToolBar/FloatingLinkToolbar.tsx
- src/components/Collaborative/Components/Source/EditorAddSources.tsx
- src/components/Collaborative/Components/Source/EditorSouceList.style.tsx
- src/components/Collaborative/Components/Source/EditorSourceList.tsx
- src/components/Collaborative/Components/Source/EditorSourcePopover.tsx
- src/components/Collaborative/Editor.style.tsx
- src/components/Collaborative/hooks/useFloatingLinkState.tsx
- src/components/Form/FormField.ts
- src/components/Source/SourceListItem.tsx
- src/pages/claim-page.tsx
- src/pages/claim-review.tsx
- src/pages/kanban-page.tsx
- src/store/store.ts
- src/store/types.ts
> Enable editor source creation w/o selecting text

- public/locales/en/kanban.json
- public/locales/pt/kanban.json
- server/claim-review-task/claim-review-task.service.ts
- server/claim-review-task/dto/get-tasks.dto.ts
- src/api/ClaimReviewTaskApi.ts
- src/components/Kanban/KanbanCol.tsx
- src/components/Kanban/KanbanView.tsx
> Implemented kanban filter to visualize assigned cross-checkings and assigned reviewers

- lib/editor-parser.ts
- server/editor-parse/editor-parse.service.spec.ts
- src/components/Collaborative/CollaborativeEditor.tsx
Reverts AletheiaFact/aletheia#1277
> Revert "HotFix: Refactored MarkUp Sources Logic"

- src/components/ClaimReview/TopicInput.tsx
Fixed topic input bug api call error by passing the dispatch function as property
> BUGFIX: Topic input error

- cypress/e2e/tests/header.cy.ts
- public/locales/en/menu.json
- public/locales/en/seo.json
- public/locales/en/verificationRequest.json
- public/locales/pt/menu.json
- public/locales/pt/seo.json
- public/locales/pt/verificationRequest.json
- server/verification-request/verification-request.controller.ts
- server/verification-request/verification-request.service.ts
- src/api/verificationRequestApi.ts
- src/components/AletheiaMenu.tsx
- src/components/TextAreaAutoSize.tsx
- src/components/VerificationRequest/VerificationRequestCard.tsx
- src/components/VerificationRequest/VerificationRequestList.tsx
- src/pages/verification-request-page.tsx
- src/pages/verification-request-review-page.tsx
> Create verification request page

- public/locales/en/verificationRequest.json
- public/locales/en/warningModal.json
- public/locales/pt/verificationRequest.json
- public/locales/pt/warningModal.json
- src/api/verificationRequestApi.ts
- src/components/Claim/CreateClaim/CreateClaimView.tsx
- src/components/VerificationRequest/VerificationRequestDrawer.tsx
- src/components/VerificationRequest/VerificationRequestProvider.tsx
- src/components/VerificationRequest/VerificationRequestResultList.tsx
> Improved Verification Request's user experience

- server/topic/topic.module.ts
- server/topic/topic.service.ts
- server/verification-request/schemas/verification-request.schema.ts
- server/verification-request/verification-request.controller.ts
- server/verification-request/verification-request.service.ts
- src/api/verificationRequestApi.ts
- src/components/ClaimReview/ClaimReviewHeader.tsx
- src/components/ClaimReview/TopicInput.tsx
This pull request introduces full CRUD (Create, Read, Update, Delete) functionality for the Verification Request Topics feature in our application.
> Enabled Verification Request Topics CRUD

- src/components/AletheiaVideo.tsx
> changed the new YouTube video link on the platform

- src/components/Collaborative/VisualEditor.tsx
- src/components/Form/ClaimReviewSelect.tsx
- src/components/SentenceReport/SentenceReportPreviewView.tsx
- src/machines/reviewTask/selectors.ts
- src/pages/claim-page.tsx
Fixed display report button, showing only when the feature flag is en…abled
Disabled select input
Enable display reports while writing the report (assigned state)
> BUGFIX: Fixed display previews button functionality

- cypress/e2e/tests/review.cy.ts
- public/locales/en/verificationRequest.json
- public/locales/pt/verificationRequest.json
- server/topic/topic.controller.ts
- server/topic/topic.service.ts
- server/verification-request/verification-request.controller.ts
- server/verification-request/verification-request.service.ts
- src/api/topicsApi.ts
- src/api/verificationRequestApi.ts
- src/components/Search/AdvancedSearch.tsx
- src/components/Search/SearchPageView.tsx
- src/components/VerificationRequest/ActiveFilters.tsx
- src/components/VerificationRequest/FilterPopover.tsx
- src/components/VerificationRequest/VerificationRequestList.tsx
- src/components/VerificationRequest/VerificationRequestSearch.tsx
- src/store/store.ts
- src/store/types.ts
page: 
fiter options: 
filters applied:
> Filter Options On Verification Request Page

- src/components/namespace/NameSpaceFormDrawer.tsx
as per https://github.com/mui/material-ui/pull/36426
> Hotfix: Fix weird behabiour with duplicated entries in Autocomplete 

- public/locales/en/debates.json
- public/locales/pt/debates.json
- src/components/Debate/DebateHeader.tsx
- src/components/Debate/DebateView.tsx
Creation of a button that open the edit mode on the debate page
closes #902
> Button that open edit mode on debate page

- docker-compose.yaml
- public/locales/pt/affix.json
Change the texts that appear on floating buttons.
> Change the texts that appear on floating buttons.

- src/components/SentenceReport/SentenceReportSummary.tsx
*add spacing in button and text font*
closes#1397
> access-source-button-spacing

- src/components/Loading.tsx
*Loading.tsx: I unbugged loading that was overlapping the header, leaving it vertically more in the center of the page*
Fixes #895 
*I tested by changing its height value from '50%' to '50vh', I looked everywhere the loading component was and I didn't find any breaks in the app*
> issues895-BugLoading

- server/claim/claim.controller.ts
- server/home/home.controller.ts
- server/personality/personality.controller.ts
- server/personality/personality.service.ts
- src/components/Debate/DebateClaimCardWrapper.tsx
- src/components/Debate/DebateHeader.tsx
*personality.service.ts: Set default to NameSpaceEnum.Main if namespace parameter is missing*
Fixes #1178 
*Fix missing data on Personality page by setting default namespace
- Previously, the const `nameSpace` was only using `this.req.params.namespace`, which caused the Personality page to not display data correctly when no namespace was provided.
- Added `|| NameSpaceEnum.Main` as a fallback, ensuring the correct data is displayed even if the namespace is missing.*
> Issue 1178 - Fix personality speeches stats

- deployment/config/config-file/development.pkl
- deployment/config/config-file/modules/service/confBase.pkl
- Configuration deploy
Once this is merged, the test environment will always require a login
> Restore the test env config to make it private and require login

- server/review-task/comment/comment.controller.ts
- server/review-task/comment/comment.module.ts
*The objective of this PR is to create a layer of security for each comments api by changing permissions so that regular users cannot create, update or delete comments.*
Fixes #1064  (issue)
*Used Insomnia to test backend comment APIs.*
**With RegularUser:**
*Returns access denied*  
**With ReviewerUser:**
*Returns found user and user Id*
> Add layers of security in comment APIs

- .github/workflows/nodejs.yml
- src/components/Footer/AletheiaSocialMediaFooter.tsx
- src/components/Footer/FooterInfo.tsx
- src/components/Header/DonateButton.tsx
- src/components/Header/HeaderContent.tsx
- src/components/Home/CTA/CTASectionButtons.tsx
- src/components/MainApp.tsx
- src/styles/colors.ts
In order to improve the branch `ufpb-labcheck` branch status for continues deployment on that environment. I am cherry-picking an important commit from it before squashing the other commits in the other branch containing only the config specific files.
To test you would need to create a new localConfig for the software and see it working.
> Revert changes to localConfig imports

- .github/workflows/aws.yml
- src/components/Home/DonationBanner.style.tsx
*Correcting the name of the color where it is called in the donation banner styles and adding the ARG environment variable in the docker image build in production*
> Correcting colors names and add ARG in production build of Donation Banner

- src/pages/about-page.tsx
*In a PR removing the enableWarningDocument feature flag, an error was added when the query was removed in the getServerSideProps function, thus breaking the about page. This PR is just to fix this*
*Open the side menu and go to the about page*
> Fixing missing query in about-page

- public/locales/en/donationBanner.json
- public/locales/pt/donationBanner.json
- src/components/Home/DonationBanner.style.tsx
- src/components/Home/DonationBanner.tsx
- src/components/Home/DonationBanner/DonationBannerButton.tsx
- src/components/Home/DonationBanner/DonationBannerContent.tsx
*The purpose of this PR is to make the final adjustments to the donation banner.*
1. *The first change involves replacing the old button with an "X," allowing the user to close it just once. This action will save a cookie and disable the banner for that user.*
2. *The "Não quero doar" and "Quero contribuir!" buttons also close the banner forever.*  
*Button design:*
*After it has been closed by the user:*
Fixes this #1470 
1. *Click the "Close Banner(X)", "Não quero doar" and "Quero contribuir!"  button one at a time.*
3. *Go to the browser's DevTools, navigate to the Application tab, and check under Cookies to see if there is one named donation_banner.*
4. *After that, verify if the banner no longer appears on any page of the platform.*
5. The responsiveness of the banner should also be …
> Latest changes to donation banner december

- server/scripts/createNovuSubscribersFromDB.ts
> Add script to create Novu subscribers from database users

- src/components/Debate/DebateHeader.tsx
*DebateHeader.tsx: Adjusting the edit button to stop overlapping over the AffixCTAButton and tweaked responsiveness*
Fixes #1423 
*1. Be logged in to the platform;
2. Create a Debate or join an existing one;
3. Hover over the AffixCTAButton and see if it overlaps the edit button;
4. Slow down the VW to see if the responsiveness adjustment is working.*
> 1423 - Fix Button Overlay

- server/claim/claim.controller.ts
- src/pages/debate-page.tsx
Ensured feature flags are queried during the render of the Debate page to make them accessible for cases involving claim reviews.
Test the components controlled by feature flags within the review drawer on the Debate page.
> fix: Query missing feature flags on Debate page render for claim reviews

- src/components/ClaimReview/ReportModelButtons.tsx
- src/components/Collaborative/Components/Source/EditorAddSources.tsx
- src/components/Personality/PersonalityCreateCTA.tsx
- src/components/Source/SourceCreateCTA.tsx
*The icon changes were made in the following files PersonalityCreateCTA.tsx, SourceCreateCTA.tsx, ReportModelButtons.tsx and EditorAddSources.tsx.*
Fixes #1612 #1619 #1622 #1643 
*1. Be logged into the platform;
2. To see the icons, simply go to the personalities view page, source creation and report page.*
> Migrate from PlusOutlined Icon (Antd) to AddIcon Icon (MUI)

- src/components/Editor/Editor.tsx
*Editor.tsx: Removed Affix and substituted for the Box (MUI), Col and Row replaced with Grid (MUI) with properties like container, item, and justifyContent to organize responsive layouts.*
Fixes #1559 #1577 
*Before*
*After*
> Migrate Grid and Box Components MUI  from Editor

- .github/workflows/nodejs.yml
*From what I read in the documentation, I didn’t find any need to adapt anything in the code. I just updated it from version v3 to v4. From what I understand, the way we use it is more straightforward and doesn’t involve advanced options or parameters that would require modification.*
> Upgraded v3 to v4 of artifact actions

- src/components/Collaborative/hooks/useFloatingLinkState.tsx
> Hot Fix by adding pt on url pattern regex to allow sources from Portugal

- src/components/About/About.tsx
- src/components/HideContentButton.tsx
*HideContentButton.tsx: Migrate HideContentButton from Ant Design to MUI using IconButton;*
*About.tsx: Replaced Ant Design Button with MUI Button, replaced Row with MUI Box for layout, updated Typography to use MUI equivalents and ensured consistent styling for paragraphs and sections.*
Fixes #1510 #1526 #1613 #1651 
> Migration HideContentButton and About

- README.md
*In this PR I changed the git clone path because the old one was out of date*
*Basically to test you must run the git clone command with the new path*
> Changing git clone path

- src/components/Footer/AletheiaInfo.style.tsx
- src/components/Footer/Footer.tsx
*Basically, I replicated the logic to keep the footer fixed at the bottom of the screen, just like before with the Ant Design library, but it wasn't done when switching from Layout.Footer to Box.*
Fixes #1809 
Before:
After:
*Test the responsiveness of the login page.*
> Fix footer layout on login page

- public/locales/en/sourceForm.json
- public/locales/pt/sourceForm.json
- server/claim/claim.controller.ts
- server/feature-flag/feature-flag.service.ts
- server/review-task/review-task.controller.ts
- server/source/source.controller.ts
- src/components/Collaborative/Components/Source/EditorAddSources.tsx
- src/pages/claim-page.tsx
- src/pages/claim-review.tsx
- src/pages/debate-page.tsx
- src/pages/kanban-page.tsx
- src/pages/source-review.tsx
- src/store/actions.ts
- src/store/store.ts
- src/store/types.ts
*This PR is to remove the feature flag for adding sources from selected texts in the report.*
Fixes #1835 
*To test, I believe you should check the functionality of adding sources to the sentence report using both the '+' button and the option to select part of the text, to verify if the changes I made only removed the feature flag and didn't break anything in this functionality. Additionally, check if it still appears in the GitLab interface after being merged.*
> Removing the feature flag from add sources

- deployment/config/config-file/modules/ory.pkl
> Fix build ory pkl

- src/components/Collaborative/hooks/useFloatingLinkState.tsx
> Hotfix: source validation regex in production

- cypress/e2e/tests/personality.cy.ts
- cypress/e2e/tests/review.cy.ts
> fix cypress

- src/components/Footer/AletheiaInfo.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/FooterInfo.tsx
*In this PR, I fixed the footer layout based on the production environment. Here are some pictures of how it turned out:*
*320px:*
780px:
1024px:
1440px:
Fixes #1844 
*Test the footer's responsiveness on different screen sizes.*
> Fixing bug in footer responsiveness

- src/components/Form/ClaimReviewSelect.tsx
*In this specific component, it defines items within the select, and the placeholder appears as one of these items. Essentially, the property I added allows the empty value to be displayed in the select. Since it starts empty, there will always be a placeholder—either 'Select the classification' or the classification itself.*
Fixes #1813 
*To test it, simply create a report and select a classification.*
> Fixing select bug without placeholder

- src/pages/supportive-materials.tsx
*supportive-materials.tsx: Instead of `Row`, i used MUI's `Grid container` to maintain the responsive structure, Antd's `Typography.Title` was replaced by MUI's `Typography` with `variant="h1"`, ensuring that the semantics were preserved and additionally, I applied styles to maintain the appearance similar to the previous version before the migration.*
Fixes #1607 
*1.Log in to the platform;
2. Click on the sandwich menu icon (top left corner);
3. Click on Supportive Materials to be directed to the Supportive Materials page.*
Before:
After:
> Migrate Supportive Materials page to MUI

- src/components/Debate/DebateTimelineWrapper.tsx
- src/components/Debate/DebateView.tsx
> Correct layout debate timeline wrapper

- src/components/PrivacyPolicy/PrivacyPolicy.tsx
*PrivacyPolicy.tsx: In this migration used the `Accordion`, `AccordionSummary`, `AccordionDetails`, `Grid`, `Typography` components from `@mui/material` and `ExpandMoreIcon` from `@mui/icons-material`. In MUI, Accordion contains the Collapse behavior from Ant Design, AccordionSummary is equivalent to the Panel header. Antd's Row translates directly to MUI's Grid and MUI's Typography has the same behavior as Antd.*
Fixes #1768 
1. Log in to the platform;
2. Click on the sandwich menu icon (top left corner);
3. Click on Privacy Policy to be directed to the Privacy Policy page.
Before:
After:
https://github.com/user-attachments/assets/8b8f3285-45b2-45c5-ade6-b8ad18faa69e
> migrated privacy policy page to MUI

- public/locales/en/notification.json
- public/locales/pt/notification.json
- src/components/Notification/NotificationCard.tsx
- src/components/Notification/NotificationIcon.tsx
- src/components/Notification/NotificationMenu.tsx
https://github.com/user-attachments/assets/812e801c-9f24-434b-9071-14a39c8e7303
> Migrating Notification to MUI

- src/components/Copilot/CopilotFeedback.tsx
In this PR, I migrated the `Rate` component to MUI. I used the `Rating` component from MUI to keep the same functionality, with a slightly different visual style.
**Before:**
https://github.com/user-attachments/assets/e6652f24-a4f1-48d1-9ec9-976c3d7b760b  
**After:**
https://github.com/user-attachments/assets/512cb561-cc14-4b45-bbdc-b1174a904572
Fixes #1570
To test it, make sure you have the required environment variables to run Copilot locally. Then, go to the Copilot pages and follow the fact-checking flow.
> Migrating copilot feedback to MUI

- server/users/users.service.ts
- src/components/Claim/CreateClaim/ClaimUploadImage.tsx
- src/components/ImageUpload.tsx
- src/components/badges/BadgesFormDrawer.tsx
#1759 
#1693 
#1531 
1. Claims
- Go to the Claim Image page, upload an image, then save.
- Confirm the new image appears wherever that claim is displayed.
2. Badges
- On the Badges page, create a new badge with an image, then save.
- Check the Badges list and the Profile page to ensure the new badge and its image appear.
- Change the image of an existing badge
> Mui upload migration

- src/components/Collaborative/Form/EditorCard.tsx
- src/components/Collaborative/Form/QuestionCard.tsx
This MR fixes an issue where input fields allowed text to overflow during character deletion, mainly affecting the Question Fields.
Fixes #1415
> Fix: Input Fields Allow Text Overflow During Deletion, Affecting Question Fields

- src/components/Claim/CreateClaim/BaseClaimForm.tsx
- src/components/Claim/CreateClaim/ClaimCreate.tsx
- src/components/Claim/CreateClaim/ClaimCreateDebate.tsx
- src/components/Claim/CreateClaim/ClaimUploadImage.tsx
- src/components/Claim/CreateClaim/UseBaseClaimForm.tsx
*When migrating the claim creation form, it was only done for the case of creating speeches, thus breaking the debate and image claim functionality. In this PR, I fixed that and encapsulated the handleSubmit logic and error management inside a useBaseClaimForm. I also redefined the finish logic inside the baseClaimForm, differentiating only the submits, one for debate and speech, and one for image claim.*
You can watch the creation of all types in these videos:
Speech:
https://github.com/user-attachments/assets/1d02e97d-ecba-41fa-9a26-029bed2ca678
Image: (this one does not finalize the process because I can't run the localstack locally)
https://github.com/user-attachments/assets/30b7bdbd-4e88-4193-88c6-47873ab92305
Debate:
https://github.com/user-attachments/assets/7e13059f-ab38-4fca-945a- …
> Fix BaseClaimForm to create image and debate

- src/components/SentenceReport/SourceSummaryDisplay.tsx
This PR fixes a layout issue in the `Typography` component where very long links (e.g. tokens, hashes, or unbreakable URLs) caused horizontal overflow and impacted responsiveness. The button next to the text also became compressed due to a rigid `width` setting.
Changes:
- Applied `word-break: break-all` to ensure long strings wrap correctly.
- Replaced fixed `width` on the adjacent button with `minWidth: "fit-content"` to preserve usability.
Fixes #1881 
- Long unbreakable strings now wrap onto the next line, avoiding overflow.
- The button next to the `Typography` text remains rea
dable and clickable regardless of adjacent content size.
- Tested across different viewport widths and font scales to confirm layout stability.
**Before:**
**After:**
> Fix: Button layout issue with long, unbroken text

- src/components/Modal/ToolbarActionsModal.tsx
*I used React Hook Form to migrate the Ant Design (antd) form.*
Fixes #1664 
Tests for delete:
https://github.com/user-attachments/assets/132758bd-52a2-4191-b966-31c3de8cd7a1
Tests for hide and unhide:
https://github.com/user-attachments/assets/54b21f05-0a68-4f12-8a72-a94753577541
*To test it, use the hide, unhide, and delete functionalities on claims.*
> Migrating toolbar form to react hook

- .github/workflows/nodejs.yml
- README.md
- docker-compose.yaml
- package.json
- In order to be fully open-source, the platform needs to have the ability to run open-source DBs, ferretdb is the choice for the mongodb dependency
- CI should test both mongodb and ferretdb to make sure we can support both as part of our infrastructure choice and requirements to be fully OSS compliant
Fixes #1060
- Introducing CI step
You can use docker-compose locally to test agains ferretdb:
```
docker compose up ferretdb postgres-documentdb
```
Or compare the results between `cypress-run` and `cypress-run-ferretdb`.
None
None
> Introduce test with ferret-db step

- src/components/Collaborative/VisualEditorProvider.tsx
- src/machines/reviewTask/selectors.ts
Production Release v1.0.6# Description
- Separated states of crossChecking and addCrossCheckingComment to enable select on the right state
When testing the review feature, it's important to cover all key user flows. Specifically, focus on the following scenario to ensure proper behavior of permissions and transitions:
1. Create a Review
Start by creating a new review as a reviewer.
2. Send to Crosschecking
Once the review is complete, transition it to the crosschecking phase.
3. Verify Crosschecker Permissions
As a crosschecker:
- Ensure that the review content is read-only (i.e., cannot be edited).
- Verify that it is …
> HotFix: Readonly on Cross Checking Select Stage Based

- src/components/Paragraph.tsx
- src/components/PrivacyPolicy/PrivacyPolicy.tsx
*This PR adjusts the styling of the Privacy Policy page with a focus on improving readability and visual organization of the content. Changing the `Grid` from `container` to `item`, ensuring better structure and behavior of the layout within the context of the main grid. Applying styling via `styled-components` to centralize and standardize page styles, removing inline and scattered styles. Update to the global `Paragraph` component, applying `text-align: justify` to improve the fluidity of reading long texts and standardize the paragraphs of the Conduct and Privacy Policy pages.*
Fixes #1864 
*1. Access the application.
2. Navigate to the Privacy Policy page.*
Before: 
After:
> Fix Inconsistency Privacy Policy page

- src/components/Collaborative/VisualEditorProvider.tsx
- src/machines/reviewTask/selectors.ts
Production Release v1.0.6# Description
- Separated states of crossChecking and addCrossChecking comment to enable select on the right state
When testing the review feature, it's important to cover all key user flows. Specifically, focus on the following scenario to ensure proper behavior of permissions and transitions:
1. Create a Review
Start by creating a new review as a reviewer.
2. Send to Crosschecking
Once the review is complete, transition it to the crosschecking phase.
3. Verify Crosschecker Permissions
As a crosschecker:
- Ensure that the review content is read-only (i.e., cannot be edited).
- Verify that it is …
>  HotFix: Readonly on Cross Checking Select

- src/components/SocialMediaShare.style.tsx
*I aligned the elements vertically using `flex-direction: column`, as they were previously displayed side by side with `display: flex` and made fine adjustments with `margin` to ensure adequate visual spacing between the elements and improve the readability of the page.*
Fixes #1860 
*1.Access the Home page.
2.Open the browser's developer tools (DevTools).
3.Adjust the screen size to 1024px or larger.
4.Check the behavior of the social media component above the footer.*
Before: 
After:
> Correcting Inconsistency in the social media layout

- src/components/Copilot/CopilotForm.tsx
During copilot usage the text area was weird size, fixed it to have a better xp
> Fix, resize input area text during copilot usage

- .github/workflows/docs.yml
Copy `localConfig.example.ts` to `localConfig.ts` during CI to prevent build failure in Storybook and Compodoc steps.
This resolves the "Module not found" error caused by the missing local configuration file during static site generation.
> fix: Add localConfig generation for Storybook build in CI

- cypress/tsconfig.json
*Removing file path in CTAButton test, in cypress tsconfig, as it was unnecessary.*
Fixes #1935 
> Update file path in cypress/tsconfig

- src/components/Dashboard/DashboardView.tsx
*This PR implements namespace filtering for dashboard components that display hidden claims and reviews. This ensures that only items in the currently selected namespace are displayed, maintaining consistency with the user's namespace context. Personalities do not have the nameSpace field, so the filter does not apply to them.*
Fixes #1172 
Steps 1:
1. Log in to the platform with Admin user;
2. Enter in /admin page;
3. Click in Dashboard to see hidden items from the main namespace;
Steps 2:
1. Enter another namespace in which the user also has the admin role;
2. Enter in namespace/admin;
3. Click in Dashboard to see hidden items from the main namespace;
Note: In any namespace, you will have to have hidden items like personality, claim and report.
> Add nameSpace filter to hidden claims and reviews in Admin Dashboard page

- server/claim-review/claim-review.service.ts
*The field used in the relationship with Claim in the ClaimReview collection is target (with targetModel: "Claim"), not claim. This adjustment ensures that the query correctly finds the document in the database, avoiding 500 errors due to null returns in the report variable.*
Fixes #1782 
*Steps:*
1. Log in platform;
2. Create Claim;
3. Review this claim by adding more than 6 sources to the check;
4. Public the sentence;
5. Open the drawer sentence check;
6. Click "Ver todas as fontes" button;
7. Expected: Open page with all sources. (Url: "personality/:personalitySlug/claim/:claimSlug/sentence/:data_hash/sources")
-
> Adjust the getReport filter to use target instead of Claim

- src/components/Collaborative/extensions/SimplePasteFilter.ts
- src/components/Collaborative/utils/getEditorConfig.tsx
Created simple paste filter removing hyperlink from text pasted by extracting only plain text
Needs proper testing before merging
> fix: preventing html source parsing error

- src/components/Login/OryLoginForm.tsx
*I adjusted the Grid column values, removing fractional numbers and increasing spacing. This ensures the layout works correctly across all Chrome-recommended screen resolutions, both in Portuguese and English.*
Fixes #2004 
*Tested login at different screen resolutions to validate layout behavior*
> Fixing overlap in login layout

- server/source/source.service.ts
*This PR adds a check to the SourceService to prevent duplicates. Now, when a user enters a link that already exists, the service generates the data_hash from the href and checks whether a Source is already registered. If it exists, the existing record is returned; otherwise, a new document is created. This ensures that there are no multiple Sources for the same link.*
Fixes #1967 
*Steps:*
1. Log in platform.
2. Create a new Verification Request and add one source.
3. Create a new Verification Request and add the same source as the previous or existing Verification Request.
Note: Previously, the platform prevented you from placing an existing source already in our database; now, as we can see in the image, the Verification Request is created with the same source.
> Prevent duplicate sources by reusing existing data_hash

- server/verification-request/state-machine/verification-request.state-machine.config.ts
- server/verification-request/state-machine/verification-request.state-machine.interface.ts
- server/verification-request/state-machine/verification-request.state-machine.service.ts
- server/verification-request/verification-request.controller.ts
- server/verification-request/verification-request.service.ts
When creating verification requests through the state machine workflow, the user context was being lost, resulting in req.user being undefined. This caused history logs to be created without proper user attribution.
The issue stemmed from a scope mismatch in NestJS dependency injection:
1. VerificationRequestService is request-scoped (uses @ Inject(REQUEST))
2. VerificationRequestStateMachineService is a singleton (default scope)
3. These services have a circular dependency resolved with forwardRef
When the forwardRef was added to fix the circular dependency, it changed how NestJS instantiates the services. The singleton
state machine service captured a reference to the verification request service in its constructor, but that reference was not
properly bound to the HTTP request context. …
> FIX: Pass User Context Through State Machine to Verification Request Service
